### ISSUE TITLE
Best practice in altering an LocalForage array?

### ISSUE THREAD

**Issue by alucardu** [localForage/localForage#1014]
I want to manipulate objects in an LocalForage array (create, update, delete etc) but I can't find anything on if this is actual possible or not. What I'm doing now is retrieving the array, change it it, and then add the array to the LocalForage to update it. 

    localforage.getItem(type).then((value) => {
      let myArray = value || []
      myArray.push({ Key: game.Key })
      localforage.setItem(type, myArray)
    }).catch(function(err) {
      console.log(err);
    });

So something like this. It would be cool if we could directly interact with the LocalForage array but that might not be possible.

**Comment by tofumatt** [comment]
Unfortunately you need to get the item, alter it, then save it. localForage isn't a database, so there are no APIs for operations that act on the data without getting it first.

Your approach is correct, and is the goal for localForage! It's meant to be a very simple and flexible API, but not have a lot of "richer" database features. 🙂
