### ISSUE TITLE
Hi, how about increase an additional method getAllItems to get all items?

### ISSUE THREAD

**Issue by femvc** [localForage/localForage#1021]
localforage.getAllItems = function() {
  return new Promise(function(resolve, reject) {
    let result = {}
    localforage.iterate(function(value, key, iterationNumber) {
      result[key] = value
    }).then(function() {
      resolve(result)
    }).catch(function(err) {
      console.error(err)
      reject(null)
    })
  })
}
// test
localforage.getAllItems().then((all) => console.log(all))

**Comment by tofumatt** [comment]
There is a plugin available that provides this functionality: https://github.com/localForage/localForage-getItems 🙂 

I think in version 2.0 or 3.0 we'll likely include this as a built-in method, but for now it is available as that plugin.
