### ISSUE TITLE
This project is dead

### ISSUE THREAD

**Issue by simon1tan** [localForage/localForage#1023]
Dexie.js looks alive and well https://github.com/dfahlander/Dexie.js

**Comment by tofumatt** [comment]
The project is still maintained, though version 1 has had core features and stability for some time now.

Dexie is awesome though! There are plenty of other libraries out there for offline storage 😄

But the project is still maintained, thanks for checking in 🙂

**Comment by its-pablo** [comment]
@tofumatt do you still consider this project alive? Seeing how there are no new releases since august 2021, I would assume this isn't worked on much anymore.
