### ISSUE TITLE
Storage event support

### ISSUE THREAD

**Issue by inf3rno** [localForage/localForage#104]
I checked the code, but I haven't found support for the storage event. Maybe I just missed it, but if not, then this is a feature request...

**Comment by TheNeikos** [comment]
Is this still a thing?

**Comment by tofumatt** [comment]
I don't think there's any interest in it at this point and I don't see the appeal, so I say we close it. If anyone disagrees let me know 😄

**Comment by TheNeikos** [comment]
Well, one thing that it is really useful for would be for things like these: https://github.com/rt2zz/redux-persist-crosstab

This would make it easier to 'just' make it work, instead of having to use `localStorage`.

**Comment by tofumatt** [comment]
Huh, interesting.

Okay, I'll keep it open then. We haven't had any traction on fixing it but after seeing that use-case I'd totally accept a patch! 😄

**Comment by thgreasi** [comment]
Since we already have https://github.com/localForage/localForage-observable , should this ticket just have cross-tab notification as a pending?

**Comment by tofumatt** [comment]
Oops, I forgot about that. Yeah, looks like that's all this is really missing.

**Comment by thgreasi** [comment]
Just opened localForage/localForage-observable#5 to track the cross-tab support. @tofumatt should we close this one and #244 and move the discussion to the plugin's repo?

**Comment by tofumatt** [comment]
Yeah, I think that's good.

@TheNeikos, please follow https://github.com/localForage/localForage-observable/issues/5 for further updates on this 😄

**Comment by thgreasi** [comment]
Just opened localForage/localForage-observable#6 for this. Any feedback would be great and could help releasing it during the weekend.
