### ISSUE TITLE
Porn spam on localForage wiki

### ISSUE THREAD

**Issue by brasofilo** [localForage/localForage#1050]
Somehow, I think this isn't a NSFW example usage of localForage. 
Not sure how to report this thing, hence this issue.

https://github.com/localForage/localForage/wiki/https:--www.xvideos.com-provocativas.-Key-key-index

**Comment by thgreasi** [comment]
Hi,
Thanks for raising and I'm sorry for the inconvenience.
Until we find a better solution I've restricted write access to the wiki page to only users with write access to the repo.
