### ISSUE TITLE
Framework support Driver for Svelte

### ISSUE THREAD

**Issue by secondl1ght** [localForage/localForage#1069]
Hello,

I have just discovered localForage and it looks like an amazing library that I would like to use. My project is using Svelte (and SvelteKit). Would it be possible to add support for this framework? Or potentially is there no additional driver required for this?

Please let me know, thanks!

**Comment by secondl1ght** [comment]
Update: I tested some basic functionality like getting and setting a record and it seems to be working, so maybe no further action is required?

**Comment by tofumatt** [comment]
localForage is a storage library that doesn't need explicit framework support; it should work with Svelte the same as any other browser JS code 🙂

**Comment by secondl1ght** [comment]
Yep you are correct, it does work and I meant to close this issue. Thanks!
