### ISSUE TITLE
.getItem() called synchronously in README.  Bug in example?

### ISSUE THREAD

**Issue by blukis** [localForage/localForage#1075]
In README.md, this line seems to be executing .getItem() synchronously.  As getItem() requires an asynchronous or promise methods, is this a documentation bug?
```
...
return localforage.getItem('key');
...
```

**Comment by DiegoAWS** [comment]
Here `localforage.getItem('key')` is a [Promise](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise)  and it's correctly written in the documentation. The `await` or `.then()` clausule should be when calling the function wrapping this return.

You can read [this](https://eslint.org/docs/latest/rules/no-return-await) for more on this topic.
