### ISSUE TITLE
require not defined in Electron-forge

### ISSUE THREAD

**Issue by abbaty48** [localForage/localForage#1079]
I am stuck with this error `Uncaught ReferenceError: require is not defined` using electron-forge with `contextIsolation = true` and `nodeIntegration = false` , i am using contextBridge in preload.js and i can't use localforage from my react component.
---
Am using:
electron: 22.1.0
react: ^18.2.0
windows 11
node: v14.17.5
localforage: ^1.10.0
---

**Comment by abbaty48** [comment]
I have fixed the problem by changing the `"main"` in `node_module/localforage/package.json` to `"main": "./src/localforage.js"`

**Comment by artus9033** [comment]
I think this issue should be reopened as it is still present with the newest `1.10.0` version. This package is a dependency of `@sentry/integrations` and therefore is probably an unpleasant cause of an unexpected problem resulting in a `require is not defined` error.

The way I was able to make it work with webpack was to make webpack ignore it:
```js
module: {
  noParse: /localforage\./,
}
```

This change, however, is a dirty hack that should not be required. I think that what's missing is another bundle & an entrypoint for `webpack` specifically that will cause that problem.

One more observation: manually replacing both occurences of `var [...] = =typeof require==="function"&&require` wityh `var [...] = false` in `dist/localforage.js` help relieve this problem as well, which confirms the above.

CC @tofumatt

**Comment by artus9033** [comment]
@tofumatt can we reopen this issue, please?

**Comment by JCraigWasTaken** [comment]
Also running into this issue
