### ISSUE TITLE
Make a new release with latest code

### ISSUE THREAD

**Issue by lobo-tuerto** [localForage/localForage#1085]
Hello! :wave: 

Was wondering if it was possible to make a new `1.x` release with the latest code.

Last one is from Aug 2021. :thinking:

**Comment by rap2hpoutre** [comment]
I guess it's a question about the status of the repository that seems to be abandonned

**Comment by tofumatt** [comment]
There's nothing new in the repo that would warrant a release. New isn't always better, localForage should still work fine 😏
