### ISSUE TITLE
vulnerability in localForage

### ISSUE THREAD

**Issue by GAP-dev** [localForage/localForage#1098]
hello!
i found vulnerability in localforage module.
where can i report this?

**Comment by rap2hpoutre** [comment]
Not here I guess since you get no answer :/ 
I guess we have to find an alternative.

**Comment by tofumatt** [comment]
@GAP-dev Hi there, I'm the maintainer. Can you email me at hi@tofumatt.com? I can provide my GPG key if you'd like to send the info in an encrypted manner. 👍🏻
