### ISSUE TITLE
doesn't working with Microsoft edge

### ISSUE THREAD

**Issue by tribhuwan-kumar** [localForage/localForage#1112]
anyone knows why ?

**Comment by nicolasembleton** [comment]
It depends what exactly doesn't work. If you use WebSQL, then it won't work anywhere as it's been deprecated. If you used IndexedDB or localStorage, it should work just fine, but if you use in a special context, for example Service Worker or Shared Workers, then only IndexedDB drive should work.

**Comment by tribhuwan-kumar** [comment]
> It depends what exactly doesn't work. If you use WebSQL, then it won't work anywhere as it's been deprecated. If you used IndexedDB or localStorage, it should work just fine, but if you use in a special context, for example Service Worker or Shared Workers, then only IndexedDB drive should work.

thanks, but it's working on linux & mac just doesn't working as expected on microsoft edge
