### ISSUE TITLE
Add API to return all keys in store

### ISSUE THREAD

**Issue by dwhogg** [localForage/localForage#136]
Suggest having a call like keys(callback) to return an array of all keys in store. Would be useful in cases of trying to do housekeeping on the store if max size being reached.

**Comment by omggga** [comment]
Hello from 2017!

Still not possible to remove several keys with one call?

Now making this one
```
Promise.all([
    localforage.removeItem(key1),
    localforage.removeItem(key2)
]).then(function(res) {
    console.log(res);
});
```

could be more beautiful if

```
localforage.removeItems([key1, key2, key3]).then(function() { } );
```

**Comment by thgreasi** [comment]
https://github.com/localForage/localForage-removeItems :)

**Comment by omggga** [comment]
Oh, thank you!
