### ISSUE TITLE
Doesn't work with Browserify (double bug)

### ISSUE THREAD

**Issue by MoOx** [localForage/localForage#174]
When I do 

``` js
var localforage = require("localforage")
```

I got this error

```
Error: module "./drivers/indexeddb" not found from "/myproject/node_modules/localforage/dist/localforage.js"
```

Normal behavior path is not good.
As a workround I've tried

``` js
var localforage = require("localforage/src/localforage")
```

But got another error with a missing 

---

```
Error: module "promise" not found from "/myproject/node_modules/localforage/src/drivers/websql.js"
```

"es6-promise" is not declared as an npm dependency & it should to be usable via npm

As a final woraround, I've done

```
npm i -D es6-promise
ln -s ../node_modules/es6-promise node_modules/promise
```

And now it's working. This should be improved because having to remap promise to es6-promise this way is seriously ugly :D

**Comment by mshwery** [comment]
dang, this is still broken with browserify

**Comment by thgreasi** [comment]
@mshwery After summing up the recent #412 & #413, you might want to take a look at how [open-flight-planner](https://github.com/Turbo87/open-flight-planner) is configured to use localforage. This **is working** both with the latest npm version and the latest master source.

**Comment by mshwery** [comment]
@thgreasi thanks for the extra info. I checked those out but their setup really isn't different than my use case, other than the fact that i'm using a separate bundle. I'm still bundling the same way, and `import`ing the same way.

I left more details here: https://github.com/mozilla/localForage/issues/412#issuecomment-135049022
