### ISSUE TITLE
Firefox private browsing: invalidStateError

### ISSUE THREAD

**Issue by ocombe** [localForage/localForage#195]
On Firefox private browsing the line 30 (https://github.com/mozilla/localForage/blob/master/src/localforage.js#L30) throws an InvalidStateError:

``` js
var supportsIndexedDB = indexedDB &&
                            typeof indexedDB.open === 'function' &&
                            indexedDB.open('_localforage_spec_test', 1)
                                     .onupgradeneeded === null;
```

The problem is that `indexedDB.open` will trigger an error because indexedDB doesn't work in private browsing and this error should be catched.
This code was added here when you were fixing the issue #150.

I added [a test](https://github.com/ocombe/angular-localForage/commit/04f55e6f71e543a7ae123a77f42cb396c2ba7d29) in my AngularJS lib to switch to local storage when this is the case, but it would be nice if it was fixed in localForage as well.

**Comment by trangsinh87** [comment]
I faced the same issue and I found the solution is that `return true;` in `onerror` function.
```
var db = indexedDB.open('db_name');
db.onerror = function() {
    return true; //it'll prevent `InvalidStateError` or `UnknownError` exception
}
```
Hope it can help someone.

**Comment by charltoons** [comment]
@trangsinh87 It saved me, thank you. 🙏

**Comment by froodian** [comment]
Did this solution stop working for anybody else ~August 25th? We started seeing the error crop up again in product then, and I currently am seeing it (from a usage where onerror is returning true, as shown above) on Firefox 55.0.3, which was coincidentally released on that date...

**Comment by tofumatt** [comment]
Huh, I don't think anyone else mentioned it but that's interesting. Was there anything in the release notes for that version that talk about IndexedDB?

**Comment by froodian** [comment]
Not that I'm seeing, no - it is possible the date is coincidental.
