### ISSUE TITLE
Give access to sessionStorage

### ISSUE THREAD

**Issue by ianb** [localForage/localForage#2]
sessionStorage has some beneficial features for which there is no real IndexedDB equivalent (I happen to use it in TogetherJS).  It would be nice if you could specifically get a sessionStorage-backed database.

**Comment by thgreasi** [comment]
Just published a [custom driver that uses sessionStorage](https://github.com/thgreasi/localForage-sessionStorageWrapper) in case someone is still interested.

**Comment by tofumatt** [comment]
Added it to the [wiki](https://github.com/mozilla/localForage/wiki/Custom-Drivers)

**Comment by jirislav** [comment]
I think it would be nice to have an optional driver choice of sessionStorage so that I could use the benefits of deserialization already being implemented within the localForage .. @thgreasi thanks for your effort! i'm going to use it ;)

**Comment by thgreasi** [comment]
@jirislav I'm happy this is useful for you :)
