### ISSUE TITLE
Inconsistent results: Windows - ok / Ubuntu - fail

### ISSUE THREAD

**Issue by klenwell** [localForage/localForage#222]
I put together a [simple fiddle](http://jsfiddle.net/klenwell/5TaX4/) to test LocalForage. It worked for me in Chrome on Windows. `setItem` callback never fires for me in Chrome on Ubuntu and I see these console errors in Firefox on Ubuntu:

```
TypeError: localforage.setItem is not a function

Error: No available storage method found.
  new Error('No available storage method found.'));
```

Again, here's the fiddle: http://jsfiddle.net/klenwell/5TaX4/

Detailed StackOverflow question here: http://stackoverflow.com/q/25007471/1093087

The only other variable I can think of would be different Internet connections.

This may be a `HelpWanted` matter. Am I doing something wrong?

**Comment by thgreasi** [comment]
Is this still an issue? Should we close it?

**Comment by klenwell** [comment]
Yes, sorry, I'll close. Never figured out what the issue was.
