### ISSUE TITLE
iOS8 & indexedDB

### ISSUE THREAD

**Issue by ocombe** [localForage/localForage#254]
It seems that Apple screwed up the iOS8 indexedDB implementation: http://www.raymondcamden.com/2014/9/25/IndexedDB-on-iOS-8--Broken-Bad
Do you know if there is anything you could do to prevent iOS8 from using indexedDB, until this problem is resolved ?

**Comment by CoIin** [comment]
Has anything change here recently? If I'm using Mac OS 10.11, or iOS 9.3.1, do I have to live with the workaround from 16 months ago?

**Comment by bradennapier** [comment]
Appears to still not work - localforage on ios = breaks entire page
