### ISSUE TITLE
Write your own driver?

### ISSUE THREAD

**Issue by jprichardson** [localForage/localForage#267]
It'd be awesome to be able to write your own drivers. It looks like https://github.com/mozilla/localForage/blob/master/src/localforage.js#L228 it's not possible ATM. Thoughts?

**Comment by UdoBretz** [comment]
I wonder if there is any example implementation on how to use the sqlitePlugin with the new custom driver support?

**Comment by thgreasi** [comment]
You can take a look at the dummy driver found in the tests folder.

On Mon, Jun 1, 2015, 01:24 Udo Bretz <notifications@github.com> wrote:

> I wonder if there is any example implementation on how to use the
> sqlitePlugin with the new custom driver support?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mozilla/localForage/issues/267#issuecomment-107253796>
> .
>
-- 
*Thodoris Greasidis <https://www.linkedin.com/in/thgreasi>*
Computer, Networking &
Communications Engineer

**Comment by roblav96** [comment]
for anyone looking:

https://github.com/thgreasi/localForage-cordovaSQLiteDriver
