### ISSUE TITLE
Namespaced Stores

### ISSUE THREAD

**Issue by ForbesLindesay** [localForage/localForage#274]
It's possible to namespace your local forage storage so that it is less likely to conflict with any other users of local storage/WebSQL/etc. by doing:

``` js
localforage.config({storeName: 'my_super_unique_prefix'});
```

However, that configuration is then shared among  all users of localForage.  What would be really useful would be a way of having an instance of local forage for each different library that uses local storage so that each library can use its own namespace.  Something like:

``` js
var myStore = localforage.namespace('my_super_unique_prefix');

// now use `myStore` instead of `localforage`
```

**Comment by RangerMauve** [comment]
Any ETA on the docs for this?

**Comment by tofumatt** [comment]
No ETA, would love contributions but if not I can try to get to it this week. It's an important feature.
