### ISSUE TITLE
Safari 8.0.3 (Mac) prompts to increase limit, does not save any data

### ISSUE THREAD

**Issue by frumbert** [localForage/localForage#352]
On Safari 8.0.3 when I try to store a file that is larger than the default / current set maximum, Safari prompts to increase it (in this case a 15MB jpeg stored in base64 encoding). If I approve the action, no data is saved (e.g. `localforage.iterate(function(err,value) { console.log(value) })` does not show the newly added key).

![screen_shot_2015-03-02_at_10_05_56_am](https://cloud.githubusercontent.com/assets/592257/6433539/adc4d79e-c0c5-11e4-8261-d5e3db27067e.png)

Edit:
According to @coulson84 in #642, this also happens in iOS 9.3.2 as well.

> Steps to reproduce
> * Add items to storage via localForage.setItem until the system prompt appears for more storage
> * Approve system prompt

> Expected outcome
> * Item should be inserted and more items can be added

>Actual outcome
> * The item being inserted at the time fails but further items can still be added

**Comment by thgreasi** [comment]
Is the related setItem() promise rejected or resolved?

**Comment by thgreasi** [comment]
Foudn some resources on that. We might to retry the operation on websql.

**Comment by thgreasi** [comment]
Have you been able to reproduce on chrome or any other browser? I've
written some code to retry setting the value, but I'm still struggling
trying to make the quota request dialog to appear on chrome.

-- 
*Thodoris Greasidis*

**Comment by frumbert** [comment]
I haven't been able to get any browser other than the older Safari's to fail - Chrome has always let me store as much as I want without a prompt. Safari (in my experience) however is good at saying it supports a feature without actually supporting it.

**Comment by thgreasi** [comment]
I'm working on [a branch](https://github.com/thgreasi/localForage/tree/websqlDbQuotaRetry) to resolve this. Can you give a try using the dist files found in there or by just visiting [this codepen](http://codepen.io/thgreasi/pen/LxxbrV)?

**Comment by frumbert** [comment]
On the codepen I'm currently just seeing `LocalForage DBQuota Pen Error Error: No available storage method found.`

**Comment by thgreasi** [comment]
Me too on latest safari. What version are you using?

**Comment by thgreasi** [comment]
I'm not sure why. I think that it also happens on LF v1.4 as well.

**Comment by frumbert** [comment]
Safari Version 10.0.3 (11602.4.8.0.1)

**Comment by thgreasi** [comment]
I can confirm that this also happens on localforage v1.4 & the current master (v1.5-pre ) on Safari 9.3.1 .
That's really puzzling.

**Comment by thgreasi** [comment]
OK so, WebSQL is still working, it's just not running inside the iframe that codepen uses.
If you right click in the preview and "Open Frame in new Tab" WebSQL is detected properly.
Alternatively you can use [this jsfiddle](https://fiddle.jshell.net/zg46nkh6/show/).
The fiddle runs, but still localforage does not save the data after the responding to the quota dialog... 😞

**Comment by frumbert** [comment]
Oh so it's another one of the Safari + Iframe issues. I should have thought of it, since I have iframes. Now Safari prompts again, asks for 5MB each time (no increase) and as you say doesn't save the data. I tried setting the value to something high (20mb) to begin with then letting the smaller values fit in - but it's the same deal. It prompts for 5MB each time regardless of how much is being asked for, and fails on the return from the dialog.

LocalForage DBQuota Pen
ready: webSQLStorage
setItem0 rejected [object SQLError]
rejected [object SQLError]
Error [object SQLError]

**Comment by thgreasi** [comment]
I pushed some new commits an about an hour. I hope to get better results tomorrow and hopefully figure out why my "retry on Quota Error" doesn't work as expected.

**Comment by thgreasi** [comment]
@frumbert, @coulson84, @tofumatt
Can you try [this one](https://fiddle.jshell.net/zg46nkh6/3/show/).
In my case it successfully stores all (16) items after asking me 2 times to increase the allowed storage size.
Once again, in case no db storage method is found, try opening the `<iframe>` in a new tab, or download and run the code locally.

**Comment by frumbert** [comment]
On my desktop Safari 10.0.3 (11602.4.8.0.1), I get prompts for 5 and 50 MB.
On my iPad Safari (ios 9.3.5), i also get prompts for 5mb then 25mb - seems good!
The log gets to `all done` in both cases.

**Comment by thgreasi** [comment]
That's great news, I will open a PR today.!
Did you also try to clear the site's data from safari preferences and rerun?
Any extra feedback based on modified fiddles or even your own apps, will be much appreciated. Thanks for helping out with this
