### ISSUE TITLE
Remove the extra instructions for webpack from README

### ISSUE THREAD

**Issue by thgreasi** [localForage/localForage#463]
Now that we are targeting the dist files for all bundlers we should remove the extra webpack instructions that suggest using the script loader plugin.
Our support should no longer be considered spotty

**Comment by tofumatt** [comment]
Good point! I’ll fix this up now :-)

**Comment by tofumatt** [comment]
Do browserify users still need [these plugins and transformers](https://github.com/mozilla/localForage/blob/master/package.json#L57) or can I remove that too?

**Comment by thgreasi** [comment]
They shouldn't need anything since we point them to the dist files. But we
should first test it on a dummy browserify & webpack project, since if they
have babel installed it might end up reading our .babelrc file and import
it's configuration.
We can't add such test case, since our project already has babel and it's
plugins. I haven't tested on dummy projects since I'm somewhat low on
available time lately.

We might better just change our note only for those users.

On Fri, Oct 9, 2015, 15:30 Matthew Riley MacPherson <
notifications@github.com> wrote:

> Do browserify users still need these plugins and transformers
> <https://github.com/mozilla/localForage/blob/master/package.json#L57> or
> can I remove that too?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mozilla/localForage/issues/463#issuecomment-146851830>
> .
>
-- 
*Thodoris Greasidis*
Computer, Networking &
Communications Engineer

**Comment by thgreasi** [comment]
Sorry if my initial issue description was inaccurate or misleading :(

On Fri, Oct 9, 2015, 18:30 Thodoris Greasidis <thgreasi@gmail.com> wrote:

> They shouldn't need anything since we point them to the dist files. But we
> should first test it on a dummy browserify & webpack project, since if they
> have babel installed it might end up reading our .babelrc file and import
> it's configuration.
> We can't add such test case, since our project already has babel and it's
> plugins. I haven't tested on dummy projects since I'm somewhat low on
> available time lately.
>
> We might better just change our note only for those users.
>
> On Fri, Oct 9, 2015, 15:30 Matthew Riley MacPherson <
> notifications@github.com> wrote:
>
>> Do browserify users still need these plugins and transformers
>> <https://github.com/mozilla/localForage/blob/master/package.json#L57> or
>> can I remove that too?
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/mozilla/localForage/issues/463#issuecomment-146851830>
>> .
>>
> --
> *Thodoris Greasidis*
> Computer, Networking &
> Communications Engineer
>
-- 
*Thodoris Greasidis*
Computer, Networking &
Communications Engineer

**Comment by stephanebachelier** [comment]
it should point to the comment about webpack warning in https://github.com/localForage/localForage/issues/577#issuecomment-224756147
