### ISSUE TITLE
Add size when minified to README

### ISSUE THREAD

**Issue by owencm** [localForage/localForage#480]
It would be great to add a rough guide (2KB? 10KB? 100KB) of the library gzipped and ungzipped to the README. Without digging it's hard to know quickly whether the network cost is worth it.

**Comment by owencm** [comment]
I was specifically wondering between using this vs [objectDB](http://objectdb.kganser.com/), which weighs in around 5KB when minified, and figured localForage is probably better in a number of ways, but it might not be worth the additional weight.

**Comment by tofumatt** [comment]
Right on.

Not opposed to adding it at all; I should localForage is 27kb minified including the Promises library; 21kb without. It’s not that lightweight a library, though I always say 21kb is still nothing compared to most people’s hero images ;-)

Anyway, If someone can grab the gzipped numbers that’d be cool, but even writing “27kb minified” is probably good.

**Comment by yash14123** [comment]
I would like some help to solve this.

**Comment by nlappe** [comment]
i know this old and probably dead, but i was looking for an indexedDB wrapper, wondered about the payload it'd add to my total app size and google sent me here :)
As i didnt find an answer either i just downloaded the lib from the cdn and compressed it myself @ version 1.7.3.
29k minified
8,8k gzipped
7.8k brotli'd

i hope i can save future people some time :)

![image](https://user-images.githubusercontent.com/8957782/73129177-fc36e600-3fdd-11ea-9e7f-66d3f2d7f939.png)

**Comment by tofumatt** [comment]
Eventually we should automate that, but if you wanted to open a PR with that text I'd happily merge it @nlappe 😄

**Comment by nlappe** [comment]
@tofumatt 
done  :)
#926

**Comment by tofumatt** [comment]
Closed in #926. Thanks @nlappe! 😄
