### ISSUE TITLE
[Discussion] Add InMemory driver as a fallback

### ISSUE THREAD

**Issue by thgreasi** [localForage/localForage#488]
As proposed in #487.
Add InMemory driver as a fallback when no driver is available.

**Comment by thgreasi** [comment]
We could use something like the [dummyStorageDriver](https://github.com/mozilla/localForage/blob/master/test/dummyStorageDriver.js) that is used for the [tests](https://github.com/mozilla/localForage/blob/master/test).
On the other hand, we could avoid serialization and just do deep clones of the objects.

**Comment by siddo420** [comment]
+1 

very important

**Comment by siddo420** [comment]
Has anybody found any solutions/workarounds for this?

this becomes important when users are using private browsing in FF.

**Comment by daviddeutsch** [comment]
I cannot confirm that this is an issue with private browsing - it seems to work just fine for me.

Could we at least have localForage fail gracefully as a short term solution?

**Comment by thgreasi** [comment]
I think that we can consider this one as resolved since [localForage-memoryStorageDriver](https://github.com/localForage/localForage-memoryStorageDriver) is available since May 2016 (sorry for not posting earlier).

@davidguttman After merging #448 we can be confident that localforage works just fine in private browsing mode too. That's because we now test whether the asynchronous initialization of a driver fails and try to setup the next preferable one (in an async & user transparent manner).

**Comment by daviddeutsch** [comment]
@thgreasi Thank you so much for getting back on this!
