### ISSUE TITLE
localforage not saving in iOS cordova Apps?

### ISSUE THREAD

**Issue by coicoronado** [localForage/localForage#490]
Hi
This isn't a bug but more like a question, after i played around with this library and try to implement it as a functionality to let a user autologin i need to set and store some information and then ask to the backend if this is ok and continue were the user left, but it seems that if i just remove the app from the background all the information is lost.

So my question is, every time i remove my app from the background i lose the data that was saved? or i'm just doing something wrong

**Comment by tofumatt** [comment]
localForage should work in iOS Cordova apps, so there is either a bug in localforage or a mistake elsewhere.

Would you be able to share the code that's acting up? Which version of iOS and localforage are you using?

- tofumatt

**Comment by coicoronado** [comment]
Hi Tofumatt and thanks for the respond
i was checking the issues that you have reported in the git repo about the
webpack thing, and after some attempt i concider another approach, which at
this momment is working correctly, so i think that i might stick to the
other approach mainly because the data is stored and reachable even when i
close the app completly, because when i reopen the app and try to get the
values stored in the localforage and even the length function always return
a null

If i have to return to use this lib i might contact you again
Thanks anyway

2015-12-18 5:03 GMT-06:00 tofumatt ☕️ <notifications@github.com>:

> localForage should work in iOS Cordova apps, so there is either a bug in
> localforage or a mistake elsewhere.
>
> Would you be able to share the code that's acting up? Which version of iOS
> and localforage are you using?
>
> - tofumatt
>
> > On 18 Dec 2015, at 00:21, coicoronado <notifications@github.com> wrote:
> >
> > Hi
> > This isn't a bug but more like a question, after i played around with
> this library and try to implement it as a functionality to let a user
> autologin i need to set and store some information and then ask to the
> backend if this is ok and continue were the user left, but it seems that if
> i just remove the app from the background all the information is lost
> >
> > So my question is, every time i remove my app from the background i lose
> the data that was saved? or i'm just doing something wrong
> >
> > —
> > Reply to this email directly or view it on GitHub.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mozilla/localForage/issues/490#issuecomment-165749234>
> .
>



-- 
"...los hombres fuertes se cuidan a si mismos; pero, los mas fuertes cuidan
a los demas..."

**Comment by judenaveenraj** [comment]
Hi @coicoronado. If you don't mind, can you let us what alternative approach you took to avoid loss of information by localforage?

**Comment by coicoronado** [comment]
Hey @judenaveenraj after some debug of this library the problem was that one of mu scripts was removing the data after i logout so as @tofumatt said it is working correctly.

Jus for the record the lib i was using is called localStorage but you can rely on the localforage library and the data stored will be there even if you dismissed the app from the background

**Comment by thgreasi** [comment]
> the problem was that one of mu scripts was removing the data after i logout so as @tofumatt said it is working correctly.
Should we close this as invalid?

**Comment by coicoronado** [comment]
@thgreasi yes you can mark it as resolved
