### ISSUE TITLE
SecurityError in Firefox when third party cookies are disabled

### ISSUE THREAD

**Issue by bodaniel** [localForage/localForage#501]
localForage is used on a web page that is iframe embedded on a second web page. This causes driverSupport to throw SecurityError (SecurityError: The operation is insecure.) Note: Firefox is used and third party cookies have been disabled.

The error occurs when driverSupport is accessing self.indexedDB. A possible solution could be to add try/catch when accessing self.indexedDB.

```javascript
// OLD CODE
//var indexedDB = indexedDB || self.indexedDB || self.webkitIndexedDB || self.mozIndexedDB || self.OIndexedDB || self.msIndexedDB;

// NEW CODE
var indexedDB = indexedDB;
if (!indexedDB) {
    try {
        indexedDB = self.indexedDB;
    } catch (e) {
        indexedDB = undefined;
    }
}
if (!indexedDB) {
    indexedDB = self.webkitIndexedDB || self.mozIndexedDB || self.OIndexedDB || self.msIndexedDB;
}
```

**Comment by bodaniel** [comment]
To see the error in action you could follow the instructions on these pages. Note: Use Firefox and disable third party cookies. Have a look at the web developer console.
https://blooming-beach-5133.herokuapp.com/
https://blooming-beach-5133.herokuapp.com/hacked

**Comment by daviddeutsch** [comment]
I can confirm this issue. (#487 is a previous discussion and the current solution is being proposed in #488)

**Comment by daviddeutsch** [comment]
This was the remaining issue for me for using localforage in a cookies-disabled environment.

Modernizr had (and resolved) a similar issue: [Modernizr/Modernizr/pull/1831](https://github.com/Modernizr/Modernizr/pull/1831)

Wrapping the ifs into a try/catch block solved the issue for me:
```javascript
    try {
        if (typeof indexedDB !== 'undefined') {
            return indexedDB;
        }
    } catch (e) {}
```

**Comment by daviddeutsch** [comment]
Thanks so much, @thgreasi and @tofumatt !

**Comment by Sembiance** [comment]
Just wanted to note that Google's JS closure-compiler removes the try/catch statement around this block as part of the SIMPLE_OPTIMIZATIONS compiliation_level. This thus then causes FF to throw a security exception if cookies are disabled.

I don't expect this to be something that localForage fixes, but I wanted to mention it here because I spent 2 hours trying to hunt down this issue and so if another dev ends up here through a Google search, hopefully this comment will save them some time :)
