### ISSUE TITLE
Add docs for the driver() & ready() methods

### ISSUE THREAD

**Issue by thgreasi** [localForage/localForage#540]
As noted in #539 we should add some docs regarding the `driver()` method and how it works  regarding runtime driver fallbacks and `ready()`.

**Comment by rdalfonso** [comment]
@thgreasi -  the localforage type definition file on https://github.com/DefinitelyTyped/DefinitelyTyped/ may need to be updated to include .ready() method. I'm using TypeScript and .ready was not intellisensed as an available method until I added it manually to my local .d.ts file.

**Comment by plaxdan** [comment]
I notice that `ready()` is [missing from the docs](https://localforage.github.io/localForage) despite being [present on the prototype](https://github.com/localForage/localForage/blob/master/dist/localforage.js#L2166). Is `ready()` intended to be part of the public API?

**Comment by tofumatt** [comment]
@plaxdan It used to be used when loading localForage asynchronously (eg via require) but doesn't have to be used anymore. That's a separate issue, but arguably it should be at least prefixed to be `_ready` as it shouldn't be needed by most developers.

**Comment by thgreasi** [comment]
A use case that ready() is still useful is when you need to let localForage
settle down on the driver that's going to be used and possibly reach to
that choice. On the other hand, we could use an other method that actually
reaches the database, like length(), for that purpose.

-- 
*Thodoris Greasidis*

**Comment by tofumatt** [comment]
Ah, true. It's a less-common usage I'm guessing but we should add docs and
treat it as still public then!

- Matthew Riley MacPherson | tofumatt.com
