### ISSUE TITLE
Documentation unusable on Firefox Windows

### ISSUE THREAD

**Issue by EpocDotFr** [localForage/localForage#554]
The [new documentation](http://mozilla.github.io/localForage/) theme of localForage pushed live several days ago is unusable, at least on Firefox /w Windows.

When scrolling it is flickering and 25% of my CPU is eated. My entire Firefox is slowed down. Even when hovering the navigation on the left.

The previous theme was perfect, why this change?

**Comment by tofumatt** [comment]
Odd, I'll check this out. I use Dev Edition of Firefox (though on Mac OS)
and it's fine.

The old theme was built with ruby and hard to maintain/out-of-date. This
new doc system allows us to avoid a build step, but I'll see what JS is
causing the issue. Thanks for the bug report!

- tofumatt

**Comment by EpocDotFr** [comment]
Yup, this is odd. Note that I tested with and without hardware acceleration enabled: same issue.

Thanks for the information!

**Comment by yairEO** [comment]
I confirm. 
Also the font is way too small for my poor eyes. X2 enlargement will do it well.

**Comment by EpocDotFr** [comment]
Tested just now (on https://localforage.github.io/localForage/), seems the issue is gone.
