### ISSUE TITLE
Retry after websql quota increment

### ISSUE THREAD

**Issue by rubenstolk** [localForage/localForage#572]
As described here: https://github.com/mozilla/localForage/blob/master/src/drivers/websql.js#L180. After the user accepts to increase the storage, the promise is still being rejected. It should retry again before rejecting...

**Comment by thgreasi** [comment]
But the user gives his ok asynchronously!? How much time should we wait? 5 secs?
Such time constrain can be too small for the user action and in the same time too large for the application to wait.

**Comment by rubenstolk** [comment]
At least in Safari (which is mostly affected by WebSQL), the error callback only happens AFTER the user accepts/rejects.

**Comment by thgreasi** [comment]
Oh, that's good :+1: I guess we can do one more retry then

**Comment by nolanlawson** [comment]
I believe iOS has [bugs with retrying](https://pouchdb.com/errors.html#not_enough_space). In my experience, the best policy is to just structure your app so that the popup _never_ occurs (which is annoying, I know).

**Comment by rubenstolk** [comment]
That issue is for very old Safari versions... What I've seen is that things
work fine af least in recent Safari's and a retry would be nice...

**Comment by thgreasi** [comment]
@rubenstolk I think that this one is resolved by #654.
Since the merged PR is doing exactly what this issue describes, I'm closing this for now.
Please re-open in case I missed something.

**Comment by rubenstolk** [comment]
@thgreasi LGTM!
