### ISSUE TITLE
Connection closed on Chrome (IndexedDB) in long sessions

### ISSUE THREAD

**Issue by dirtybit** [localForage/localForage#581]
We have a multiple instance localForage setup in which we have two stores. There is a case where we encounter the following error:

```
InvalidStateError: Failed to execute 'transaction' on 'IDBDatabase': 
The database connection is closing.
```

One thing that caught my eyes, this issue happens after a long time (duration: 8000 - 10000 secs, yes seconds :)) after frontend app initialized. This made me think that the connection might get lost .

According to our logs, this has ben observed ~500 times in the last two days. It happens only on Chrome. Here is the distribution of browser versions:

```
0.47%   Chrome 53.0
8.04%   Chrome 49.0
5.91%   Chrome 52.0
85.58%  Chrome 51.0
```

**Comment by nolanlawson** [comment]
If you can reproduce, this would be an excellent bug to file on Chromium itself. We have observed the same problem in PouchDB (only happens with Chrome, very sporadic and rarely reproducible).

**Comment by pmgower** [comment]
@dirtybit have you been able to reproduce this issue?  I might have a similar issue going on.  Reported [mine here](https://github.com/localForage/localForage/issues/629)

**Comment by stkao05** [comment]
We also observed this issue daily, about 200 incidences a day and mostly from Chrome browser (98%). 

____

While there is certainly an issue with Chrome indexedDB, there is a room for the client (localforage) to better handle connection closed issue - such as re-establish IDBDatabase connection when connection is unexpectedly close. The [onclose](https://developer.mozilla.org/en-US/docs/Web/API/IDBDatabase/onclose) listener could be used for such an purpose.

Currently localforage does not handled broken connection and there isn't an API for app to reestablish connection themselves. So apps that encounter this issues basically run into a dead-end.
