### ISSUE TITLE
Re-enable Travis-ci integration

### ISSUE THREAD

**Issue by thgreasi** [localForage/localForage#589]
@tofumatt it seems that after moving localforage under the localforage organization, travis-ci has stopped working. Please re-enable it, since I think I don't have the rights.

**Comment by tofumatt** [comment]
Oh, good call. You should have admin rights on localForage but I’ll check
it out later if you can’t get it working to both make sure you have full
access and enable it. :-)

**Comment by thgreasi** [comment]
We probably have to update the `.travis.yml` with the new repo and also possibly update the secures.

**Comment by tofumatt** [comment]
This has been fixed 😄
