### ISSUE TITLE
Cannot initialize with memoryStorageDriver

### ISSUE THREAD

**Issue by daviddeutsch** [localForage/localForage#594]
Following up on #488 - I've been trying for quite a while to make localForage initialize with `setDriver` but cannot get `memoryStorageDriver` to be used.

Even when doing a complicated dance like:

```javascript
localforage.ready().catch(function(err) {
    if (err.message == 'No available storage method found.') {
        localforage.defineDriver(memoryStorageDriver).then(function() {
            localforage.setDriver(memoryStorageDriver._driver).then(function() {

                localforage.ready().then(function(){
                    initMyDB();
                });
            });
        });
    } else {
        initMyDB();
    }
});
````

In my `initMyDB()`, I end up getting the same "No available storage method found." error.

I found the apparently related #176, but it seems that that one is outdated since `ready` has been changed in #448.

Does anybody have an idea what's going on here?

**Comment by thgreasi** [comment]
Hi there.
Just created a [jsfiddle example](https://jsfiddle.net/dp2dzyL9/) (and added it to [the respective README](https://github.com/localForage/localForage-memoryStorageDriver/blob/master/README.md)) based on [the respective example found in the repo](https://github.com/localForage/localForage-memoryStorageDriver/blob/master/examples/index.html).
I hope it works for you.
Feel free to re-open or add extra inquiries to this issue.

**Comment by daviddeutsch** [comment]
Oh my, how embarrassing. You are of course right, @thgreasi - it works perfectly fine like that.

My issue was actually that I created additional instances via `createInstance()` later in the code and just assumed it would take the same additional drivers as previously initialized.

Sorry, should have done more due diligence - thanks so much for pointing me on the right path!
