### ISSUE TITLE
Vue.JS

### ISSUE THREAD

**Issue by Claercio** [localForage/localForage#597]
Add support to Vue.JS

**Comment by amilajack** [comment]
Support should not be directly added for a specific library. Instead, you should use a library that wraps around localForage.

**Comment by tofumatt** [comment]
Vue seems like React components, you'll want to write some kind of wrapper for Vue. That's no t something localForage will be doing in the core library.

You can look at other repos in this organisation to see wrappers for Backbone, Angular, etc to see how those work for inspiration 😀
