### ISSUE TITLE
Chaining multiple sets with a catch

### ISSUE THREAD

**Issue by pliablepixels** [localForage/localForage#598]
Good day! Thanks for this lovely library

I am trying to do a series of `setItems` sequentially. It is critical that I call `continueInitialInit()` whether this fails or succeeds. Can you comment if I am doing this the right way ? I'm basically returning `setItem` and using it to chain subsequent `.then` and there is a `.catch` at the end hoping that is what will be called if anything fails. Is this a correct sequence?

```
 localforage.setItem('defaultLang', dl)
                        .then (function() {
                            return localforage.setItem('isFirstUse', ifu);
                        })
                        
                        .then (function() {
                            ZMDataModel.zmLog (">>>>migrated isFirstUse...");
                            // lets encrypt serverGroupList
                            ZMDataModel.zmLog ("server group list is " + JSON.stringify(sgl));
                            var ct = CryptoJS.AES.encrypt(JSON.stringify(sgl), zm.cipherKey);
                            ZMDataModel.zmLog ("encrypted server group list is " + ct);
                            return localforage.setItem('serverGroupList', ct);
                        })
                        .then (function() {
                            ZMDataModel.zmLog (">>>>migrated serverGroupList...");
                            return localforage.setItem('defaultServerName',dsn);
                        })
                        .then (function() {
                            ZMDataModel.zmLog (">>>>migrated defaultServerName...");
                            ZMDataModel.zmLog (">>>>Migrated all values, continuing...");
                            //ZMDataModel.migrationComplete();
                            continueInitialInit();
                        })
                        .catch (function(err)
                        {
                            ZMDataModel.zmLog ("Migration error : " + JSON.stringify(err));
                            continueInitialInit();
                        });
```

**Comment by thgreasi** [comment]
If all the non-localforage functions/methods that you are using are synchronous, then it seems correct for your use case. Are you facing an issue?

**Comment by pliablepixels** [comment]
Thanks for the confirmation! No, not yet. I made a release for my app that was using `localstorage` previously and this code (without the catch) was what I was using to migrate to `localforage` and it was getting stuck in the middle making the app non functional. My _guess_ is one of the setItems was failing (don't know why) and `continueInitialInit` was not being called because I did not have a `catch()`. I wanted to re-confirm this is the right pattern to use before I sent another beta release out (as I can't replicate this failure). If you don't mind, may we keep this issue open for a day ? I'd like my users to try this code and if it still gets stuck/fails and does not call `continueInitialInit()` I'll post here/else close it. Thanks!

**Comment by thgreasi** [comment]
OK

**Comment by pliablepixels** [comment]
Hello, it looks like when I use `localforage`  with `cordova-sqlite-storage`, certain Android phones completely freeze when I write string values that are large (3000 chars). Switching to indexDB or webSQL via `localforage` seems to work, so I assume its a sqlite plugin issue and not an issue with local forage. So I posted the issue [here](https://github.com/litehelpers/Cordova-sqlite-storage/issues/533).

Thanks.
