### ISSUE TITLE
What's the right way to use localforage and webpack?

### ISSUE THREAD

**Issue by ezzatron** [localForage/localForage#599]
After looking through lots of old tickets, I'm pretty confused about how I'm *supposed* to use localforage + webpack together. Using it without any special treatment *does* work, but I get this warning:

```
$ make build
node_modules/.bin/webpack --debug
Hash: f7ecb9aab38b49b3370e
Version: webpack 1.13.2
Time: 1851ms
  Asset     Size  Chunks             Chunk Names
todo.js  1.35 MB       0  [emitted]  main
   [0] multi main 40 bytes {0} [built]
    + 513 hidden modules

WARNING in ./~/localforage/dist/localforage.js
Critical dependencies:
7:484-491 This seems to be a pre-built javascript file. Though this is possible, it's not recommended. Try to require the original source to get better results.
 @ ./~/localforage/dist/localforage.js 7:484-491
```

I'm using localforage 1.4.2 and webpack 1.13.2.

**Comment by thgreasi** [comment]
That's a simple warning and shouldn't be considered as something bad. Localforage uses browserify for bundling (and rollup and derequire) and your webpack just detects it and warns that you are bundling a pre-bundled file.
I would like to start a discussion about dropping derequire and using just rollup and concatenating the promises polyfill on the top (instead of requiring it). Such a move would allow us to get rid of that warning + we could also add an es6 dist file (that starts to be increasingly useful with all the new build/bundling systems).

**Comment by ezzatron** [comment]
Sounds good. Thanks for the explanation.

**Comment by jmalonzo** [comment]
@ezzatron in the interim you can tell webpack to exclude parsing the localforage module via the noParse config - 

`noParse: [new RegExp(path.resolve(__dirname, '/node_modules/localforage/dist/localforage.js'))]`

HTH.

**Comment by ezzatron** [comment]
@jmalonzo Thanks, I was able to suppress the warning with `noParse`.

**Comment by tofumatt** [comment]
That warning just means you're using a prebuilt repo, which localforage is.
It's nothing to worry about 😄

- Matthew Riley MacPherson | tofumatt.com

**Comment by tofumatt** [comment]
Oops, I replied to this via email not seeing it was closed. Sorry for the noise.

**Comment by jasan-s** [comment]
I added the following  to webpack module `noParse: [new RegExp(path.resolve(__dirname, '/node_modules/localforage/dist/localforage.js'))]` 

but the warnings remain

**Comment by ezzatron** [comment]
@jasan-s: Here's the configuration that worked for me: [webpack.config.js](https://github.com/ezzatron/single-page-todo/blob/master/webpack.config.js)

**Comment by jasan-s** [comment]
thanks, @ezzatron  but still getting the pre-built javascript Warnings for both webpack- dev and webpack -p

**Comment by goodhyun** [comment]
Try with uppercase F.
 `noParse: /node_modules\/localForage\/dist\/localforage.js/`
if you are importing from 'local**F**orage'
... even if your folder in node_modules is localforage.

**Comment by therockstorm** [comment]
For Gatsby, create (or modify) gatsby-node.js:

`exports.modifyWebpackConfig = ({ config, stage }) => {
  config.merge({
    module: {
      noParse: [new RegExp('node_modules/localforage/dist/localforage.js')]
    }
  });
}`
