### ISSUE TITLE
Q: local cache have limit.?

### ISSUE THREAD

**Issue by shangliyang** [localForage/localForage#601]
question 1:
           size        : 4980736, // Size of database, in bytes. WebSQL-only for now.
The local cache can only save the size of the data? local cache have limit.?

question 2: How to calculate the size of the data that has been stored?

**Comment by tofumatt** [comment]
The local cache has a default limit in WebSQL. You can increase it with the
config method but the default size prevents prompts from Safari asking the
user to allow storage.

There is no way to inspect the current size used.

- Matthew Riley MacPherson | tofumatt.com
