### ISSUE TITLE
npm publish?

### ISSUE THREAD

**Issue by Kreozot** [localForage/localForage#607]
Hello. Why don't you publish last changes to npm?

I was about to do pull request which already has been merged, but not published yet (fix warning in fullyReady function in indexeddb.js) :)

`npm publish` please! Thank you!

**Comment by tofumatt** [comment]
Ah okay, we publish automatically when a new version is released but looks like I need to make one.

I'll do it now and it should be about thirty minutes from now (maybe less). 😄

**Comment by tofumatt** [comment]
Looks like 1.4.3 just landed on NPM. Thanks for filing the issue!

**Comment by Kreozot** [comment]
Thanks a lot!
