### ISSUE TITLE
DataCloneError: Failed to execute 'put' on 'IDBObjectStore': An object could not be cloned.

### ISSUE THREAD

**Issue by keyiis** [localForage/localForage#610]
When i setItem then get error
`DataCloneError: Failed to execute 'put' on 'IDBObjectStore': An object could not be cloned.`

**my code:**
```
this.cacheOrders.push(order);// success!
 let str = JSON.stringify(this.cacheOrders);// success!
 console.log(JSON.parse(str));// success!
return localForage.setItem(this.cacheOrdersKey,this.cacheOrders);// error!
```

if i change
`return localForage.setItem(this.cacheOrdersKey,this.cacheOrders);`
to
`return localForage.setItem(this.cacheOrdersKey,JSON.stringify(this.cacheOrders));`
then success,If so, why would I want to use localForage.

**Comment by keyiis** [comment]
@tofumatt below is object what i trying to store:
`["[{\"received\":0,\"entries\":[{\"_item\":{\"pic\":[\"d:/work/nodejs/angular/angular2-electron/output/electron/build/pic/898478da-e0a0-47e2-aa38-06f0670f5a06.jpg\"],\"id\":1,\"code\":\"www\",\"name\":\"www\",\"py\":\"www\",\"stock\":7,\"price\":8,\"desc\":null,\"created_at\":\"2016-09-26T10:07:19.281Z\",\"updated_at\":\"2016-10-10T08:48:11.904Z\",\"fcat\":3,\"foperator\":null,\"kpos_windowcat_item\":{\"created_at\":\"2016-09-28T05:18:20.709Z\",\"updated_at\":\"2016-09-28T05:18:20.709Z\",\"item_id\":1,\"windowcat_id\":1}},\"_count\":1,\"_price\":8},{\"_item\":{\"pic\":[],\"id\":2,\"code\":\"gggg\",\"name\":\"gggg\",\"py\":\"gggg\",\"stock\":5,\"price\":19,\"desc\":null,\"created_at\":\"2016-09-26T10:07:33.147Z\",\"updated_at\":\"2016-10-10T08:47:55.735Z\",\"fcat\":2,\"foperator\":null,\"kpos_windowcat_item\":{\"created_at\":\"2016-09-26T10:08:24.838Z\",\"updated_at\":\"2016-09-26T10:08:24.838Z\",\"item_id\":2,\"windowcat_id\":1}},\"_count\":1,\"_price\":19}],\"code\":\"1476179732738\"}]",{"received":0,"entries":[{"_item":{"pic":[],"id":2,"code":"gggg","name":"gggg","py":"gggg","stock":5,"price":19,"desc":null,"created_at":"2016-09-26T10:07:33.147Z","updated_at":"2016-10-10T08:47:55.735Z","fcat":2,"foperator":null,"kpos_windowcat_item":{"created_at":"2016-09-26T10:08:24.838Z","updated_at":"2016-09-26T10:08:24.838Z","item_id":2,"windowcat_id":1}},"_count":3,"_price":19}],"code":"1476235781952"}]`

**Comment by tofumatt** [comment]
Ah, okay, if the object contains a function it can't be stored inside a database as it can't save functions.

You'll need to remove the function from the object you're trying to save before saving it. You can see the types of objects localForage can store here: https://localforage.github.io/localForage/#data-api-setitem

**Comment by thgreasi** [comment]
What I'm doing lately in such cases is to define an "class" and place all the methods in the prototype.
Most of the time this is enough to make the object serializable and requires an extra step when retrieving form localforage:
```js
function User () {}
User.prototype.hello = function () {
  console.log('Hi');
}

var userData = localforage.get('user');
var user = Object.assign(new User(), userData);
```
Please confirm whether this actually works for you.

**Comment by thgreasi** [comment]
Keep also in mind that storing Promises in properties might cause serialization troubles as well.

**Comment by keyiis** [comment]
@thgreasi  the object from other package and i can't modify structrue,so i must stringify before store.if localforage can judge object can't clone and automatic stringify to store?

**Comment by milahu** [comment]
debug helper to find the `could not be cloned` value

```js
// npm i -D lodash-es deepdash-es @types/lodash-es
import _lodashModule from 'lodash-es';
import _deepdashModule from 'deepdash-es';
const lodash = _deepdashModule(_lodashModule);

async function writeCache(key, value) {
  try {
    await set(key, value);
  }
  catch (error) {
    // find error location
    const valDesc = (
      error.message.match(/^Failed to execute 'put' on 'IDBObjectStore': (.*) could not be cloned\.$/) ||
      [null, null]
    )[1]
    if (valDesc == 'function () { [native code] }') {
      // DOMException: Failed to execute 'put' on 'IDBObjectStore': function () { [native code] } could not be cloned.
      const path = lodash.findPathDeep(value, (val) => typeof val == 'function')
      console.error(`${error}\n\nvalue contains a function: value.${path}`)
    }
    else {
      console.error(error)
    }
  }
}

const value = {
  a: [
    {
      b: () => 1
    }
  ]
}

writeCache("asdf", value)

// error: value contains a function: value.a[0].b
```
