### ISSUE TITLE
transform localStorage to localforage

### ISSUE THREAD

**Issue by aahedi** [localForage/localForage#616]
Help me http://stackoverflow.com/questions/40351612/how-to-change-localstorage-script-to-localforage-script

**Comment by tofumatt** [comment]
localForage is **not** a drop-in replacement for localStorage. The [localForage API is documented here](https://localforage.github.io/localForage/); it is not synchronous so you can't simply find+replace `localStorage` with `localforage`.

You also can't access keys as properties on localForage (`localforage.unit` in your example will not work). You would need to do:

```js
localforage.get('unit')
  .then(function(value) {
    console.log(value);
  });
```
