### ISSUE TITLE
Pre-built issue with webpack

### ISSUE THREAD

**Issue by Darkbladecr** [localForage/localForage#617]
I have been using localForage with webpack `import localforage from 'localforage'` and have found importing the package can cause this warning:
```
WARNING in ./~/localforage/dist/localforage.min.js
Critical dependencies:
7:413-420 This seems to be a pre-built javascript file. Though this is possible, it's not recommended. Try to require the original source to get better results.
 @ ./~/localforage/dist/localforage.min.js 7:413-420
```
Are there any suggestions as how we can remove these warnings?

**Comment by thgreasi** [comment]
@Darkbladecr Hi there.

As noted in #567, #577, #599
> That's a simple warning and shouldn't be considered as something bad. Localforage uses browserify for bundling (and rollup and derequire) and your webpack just detects it and warns that you are bundling a pre-bundled file.

Using webpack's `noParse` configuration option will allow you to remove the warning:
```js
// webpack.config.js
module.exports = {
    module: {
        // ...
        noParse: [new RegExp('node_modules/localforage/dist/localforage.js')]
    }
};
```
An other way would be to configure webpack to target the`src` files directly and rebuild localforage but that's probably an overkill.
