### ISSUE TITLE
1.4.3 always fails blob support test

### ISSUE THREAD

**Issue by AshleyScirra** [localForage/localForage#618]
In localforage 1.4.3 (testing in Chrome) it always fails `_checkBlobSupportWithoutCaching` because it passes a database instead of a transaction, which leads to this call:

`txn.objectStore(DETECT_BLOB_SUPPORT_STORE).put(blob, 'key');`

which throws `TypeError: txn.objectStore is not a function` because `txn` is really an `IDBDatabase`. It is clearly passing a database up the callstack from `_checkBlobSupport(idb)`, initiated by a `setItem` call with a blob type (`_checkBlobSupport(dbInfo.db)`).

Execution jumps down in to a promise `catch` which returns false, and it ends up saving an encoded blob rather than a normal blob directly.

localforage 1.4.0 does not appear to be affected so this seems to be a recent regression.

Demo: https://www.scirra.com/labs/bugs/localforage-blob/
That basically just does `localForage.setItem("foo", new Blob(["bar"]))`. Open dev tools and set pause on all exceptions.

**Comment by tofumatt** [comment]
Thank you for the report and really sorry it took me so long to address this.

I'm a bit swamped until mid-December with Mozilla add-ons stuff so I won't be able to check this out until then myself. Thanks for the detailed report; should make it easier to patch. 👍

**Comment by AshleyScirra** [comment]
Any news on this?

**Comment by tofumatt** [comment]
I'm sorry, we've been really busy with a new add-ons frontend project and it's still eating up a lot of my time for side projects. I don't yet know when I'll be able to look at this; if someone else could patch it I could probably more quickly review it than write the code myself, but I will try to check it as soon as I can if no one else can look! Sorry!

**Comment by thgreasi** [comment]
Just opened PR #643, can I get an extra confirmation that it works?

**Comment by thgreasi** [comment]
@AshleyScirra any feedback on this? @tofumatt does it look ok to you at least?

**Comment by AshleyScirra** [comment]
I'd test it, but I can't see a convenient way to effectively download a release with a PR merged. I don't use GitHub much. Do I have to manually copy-paste the PR in to master?

**Comment by thgreasi** [comment]
Going to the PR and finding the dist file and pressing `view` and then `raw` you will give you [the source of the file](https://raw.githubusercontent.com/thgreasi/localForage/17f24b79629a7b50d43119a41511a89221a78d0f/dist/localforage.js).

**Comment by thgreasi** [comment]
@AshleyScirra any feedback on this?

**Comment by AshleyScirra** [comment]
I tested localforage.nopromises.js from PR #643, and it looks like blobs are stored correctly again.

**Comment by thgreasi** [comment]
Great!
