### ISSUE TITLE
Issue calling localForage inside a function (Angular/Ionic)

### ISSUE THREAD

**Issue by minhazfm** [localForage/localForage#619]
Hey everyone,
Been running into an issue where I'm creating a factory/service in my Ionic app using Angular, which stores and retrieves basic data from a localForage instance I've instantiated. For some reason, the localForage function call returns undefined when wrapped around a basic getter or setter function. Not sure if this is an issue, or if I'm doing something wrong here? The factory code snippet is below. So when I call `UserData.getStoredLoginData()` anywhere in my app, it runs undefined, but if I call `localforage.getItem` directly it works fine. Not sure what's going on...

```
.factory('UserData', function() {

  var _getStoredLoginData = function() {
    localforage.getItem('rememberMe', function(err, value) {
      if (err)
      {
        return null;
      }
      return value;
    });
  }

  return { getStoredLoginData: _getStoredLoginData }

})
```

**Comment by tofumatt** [comment]
You aren't returning the localForage `getItem` call or passing a callback to it, so your function should return undefined.

localForage uses an async API, so if you want to wrap it, you'd need to return and handle a Promise. See: https://localforage.github.io/localForage/#data-api-getitem
