### ISSUE TITLE
Example not working

### ISSUE THREAD

**Issue by murugesh-smp** [localForage/localForage#62]
localForage  example code. 

example code return a Reference error : 
when i try with 
          localForage.getItem('....
          localForage.setItem('....
it return
ReferenceError: localForage is not defined
         localforage.getItem('....
         localforage.setItem('....
is working.

**Comment by cinder92** [comment]
i receive the same issue from localforage-angular

**Comment by tofumatt** [comment]
@cinder92 Which example are you trying to run?

**Comment by KeynesYouDigIt** [comment]
I get the same error running https://mozilla.github.io/localForage/?javascript#setitem

Can this be run server side? how shoud I initialize the db this client side?

**Comment by tofumatt** [comment]
@KeynesYouDigIt If you're having an issue running code please open a new issue, as this one is closed and over two years old.

Additionally, you can't run localForage on the server. See https://mozilla.github.io/localForage/#installation for info on installation.

**Comment by KeynesYouDigIt** [comment]
sorry guys, I just forgot to include the script right. I am dumb and thanks for the link!

**Comment by tofumatt** [comment]
No worries, glad you got it working!
