### ISSUE TITLE
Webkit warnings

### ISSUE THREAD

**Issue by Darkbladecr** [localForage/localForage#621]
When using localForage I receive several warnings in the console log:

> 'window.webkitStorageInfo' is deprecated. Please use 'navigator.webkitTemporaryStorage' or 'navigator.webkitPersistentStorage' instead.
> 'webkitIndexedDB' is deprecated. Please use 'indexedDB' instead.

![screen shot 2016-11-12 at 12 52 03](https://cloud.githubusercontent.com/assets/4283896/20237905/f135c01a-a8d6-11e6-841a-f6208205f0e8.png)

**Comment by thgreasi** [comment]
The interesting thing is that we don't actually use the prefixed namespaces when the standardized indexedDB object is available. I will try to make the warning disappear somehow.

**Comment by Darkbladecr** [comment]
I have been using localforage with [redux-persist](https://github.com/rt2zz/redux-persist) 
I have added an [issue](https://github.com/rt2zz/redux-persist/issues/208) there as well, just in case it is due to the way they use localforage.

**Comment by thgreasi** [comment]
I wasn't able to reproduce on Chrome (guessing from your screenshot) neither on stable v54 nor on unstable v56. Can you provide an example codepen that reproduces your issue?

**Comment by Darkbladecr** [comment]
Couldn't find a CDN for ng-redux and not sure how to import correctly with codepen, but ultimately here is my basic setup:
http://codepen.io/anon/pen/pNyNvL?editors=1010

**Comment by thgreasi** [comment]
Still can't find a way to reproduce. What version of chrome are you using?
Here is an older & simpler [pen](http://codepen.io/thgreasi/pen/ojYKeE). I hope it helps you isolate the steps to reproduce the warning.

**Comment by thgreasi** [comment]
Any feedback on this? Were you able to isolate the issue in a codepen?

**Comment by Darkbladecr** [comment]
Let me try to recreate on a new project. I can't get the node_modules I use to load on codepen so I'll upload a zip,

**Comment by Darkbladecr** [comment]
I can't seem to reproduce. For fullness here is the sample:
[counter.zip](https://github.com/localForage/localForage/files/607223/counter.zip)

You can close.

**Comment by thgreasi** [comment]
@Darkbladecr thanks for the detailed report. I will give it a second look during the weekend and reach you in case I come up with anything.
Thanks for your collaboration on this.
