### ISSUE TITLE
safari 10.0.1 / 10.1 strange script execution 

### ISSUE THREAD

**Issue by frumbert** [localForage/localForage#623]
Strange behaviour for me under Safari, with jQuery (3). I'm using the default ready handler to bind some elements. In my script I log "a" and then "b" and then "cache loaded" and the script stops executing (how far through the ready handler the logging gets depends on how long getItem takes to return - once localforage returns its value, script execution stops).

    $(function() {

    console.log("a");

	localforage.getItem("cache", function(err, value) {
           console.log("cache loaded");
       });

    console.log("b");

    $("nav").on("click","a", function(e) {
       e.preventDefault();
    });

    console.log("c");

    $("article").on("click","a[data-provider]", function(e) {
       e.preventDefault();
    })

    });

Seems to depend heavily on how much work is being done in each of the functions inside the ready, and how long localforage takes to return. But returning a value is preventing safari from executing more script.

(Safari 10.0.1 and safari technology preview 10.1 - no extensions).

**Comment by thgreasi** [comment]
Hi there.
First of all I would suggest you to upgrade to jquery v3.1+ since v3's ready() implementation had some issues.
The logging sequence seems logical since localforage calls are asynchronous, but I'm not sure why "c" isn't logged.
Does removing the getItem() call makes "c" to get printed? Any chance that $("nav").on() causes the issue?

**Comment by frumbert** [comment]
ready is working; removing localforage means the script executes as expected. Seems like a race / concurrency thing - I'll have to try some radical restructuring (except it works beautifully everywhere except Safari)

**Comment by thgreasi** [comment]
What version of localforage are you using? Any chance that you are using an older one and browsing in private mode?
I was not able to reproduce, [Here is a pen to fork](http://codepen.io/thgreasi/pen/ojYKeE) in case you are able to reproduce your issue?

**Comment by thgreasi** [comment]
Any feedback on this? Were you able to isolate the issue in a codepen?

**Comment by thgreasi** [comment]
I'm closing this for now because of inactivity.
Please re-open with further information about the issue persists.
