### ISSUE TITLE
Uncaught ReferenceError: localforage is not defined

### ISSUE THREAD

**Issue by fytriht** [localForage/localForage#624]
<img width="768" alt="screen shot 2016-11-21 at 11 49 20" src="https://cloud.githubusercontent.com/assets/20026577/20470257/b4c2bdf6-afe1-11e6-93ff-6fd4f06eff8c.png">
I copied a project (including the node_modules file) to another computer. The project works totolly fine in the old computer,   but i got this error in the new computer.

BTW, i am not sure if this is relevent: the project was running in Windows system, and now i want it running in os x.

**Comment by fytriht** [comment]
It looks like the problem is caused by operating system differences(os x / windows), because it works fine in my colleuge's PC, and my old PC. only my mac has this error.
any idea? thanks

**Comment by thgreasi** [comment]
One of the two environments is probably running an older version of node/npm.
How about deleting the node modules folder and reinstalling them? Does it work? Is there a reason you want to avoid it?
Does it work on a new project? I guess that we should close this and mark as a question.

**Comment by MongolOverseer** [comment]
I'm having the same problem here.

Last thing I tried was having only index.html and the localforage library. In the index.html I of course had
`<script src="localforage/src/localforage.js"></script>
 <script>localforage.config();</script>`

Still I get the error:
`Uncaught ReferenceError: localforage is not defined`

**Comment by thgreasi** [comment]
You should not target the `src/localforage.js` directly. Please use the one found in the `dist` folder.
Please chech the (just updated) README.

**Comment by MongolOverseer** [comment]
Ah, that worked. Thanks for the help.

**Comment by thgreasi** [comment]
Have a funny LF weekend!

**Comment by luochenggang** [comment]
> <img alt="screen shot 2016-11-21 at 11 49 20" width="768" src="https://cloud.githubusercontent.com/assets/20026577/20470257/b4c2bdf6-afe1-11e6-93ff-6fd4f06eff8c.png">
> 
> I copied a project (including the node_modules file) to another computer. The project works totolly fine in the old computer, but i got this error in the new computer.
> BTW, i am not sure if this is relevent: the project was running in Windows system, and now i want it running in os x.

xxxxxxxxxx
