### ISSUE TITLE
Throws on server-side in SSR applications

### ISSUE THREAD

**Issue by swernerx** [localForage/localForage#627]
When using the library for redux-persist in my local application I have issues. The problem seems to be that it throws - at import level - when being referenced in any file - even if not used at all. This is problematic especially for applications which use server-side-rendering (SSR) and share common code parts like the redux initialization. With ES2015 in our code it's not even possible to import the module conditionally.

**Comment by thgreasi** [comment]
Even though this is a library primarily focused to be used on the client, can you provide any further info about the error that you are receiving?

**Comment by thgreasi** [comment]
Any feedback on this?

**Comment by thgreasi** [comment]
Any chance this might be related to the situation described in #626 ?

**Comment by thgreasi** [comment]
Closing this for now because of inactivity. Feel free to reopen with extra info or follow up in an other issue.

**Comment by thgreasi** [comment]
Fixed by #633 planned to be released as v1.5
