### ISSUE TITLE
data null after storing to IndexDB (Angular)

### ISSUE THREAD

**Issue by JamieVGroupClaes** [localForage/localForage#628]
![image](https://cloud.githubusercontent.com/assets/24246168/20706564/2ceadbdc-b628-11e6-8070-9012c820b99f.png)

![image](https://cloud.githubusercontent.com/assets/24246168/20706551/2429693c-b628-11e6-9e33-b27025bc3edd.png)

![image](https://cloud.githubusercontent.com/assets/24246168/20706573/3b6599b8-b628-11e6-8024-b36a68c0daf8.png)

![image](https://cloud.githubusercontent.com/assets/24246168/20706469/c9d09690-b627-11e6-88e9-30743bd0f50d.png)

**Comment by JamieVGroupClaes** [comment]
omg TT-Docs => TT-docs, back-end issue

**Comment by thgreasi** [comment]
:)
