### ISSUE TITLE
LocalForage generates a rejected promise when imported in node.js

### ISSUE THREAD

**Issue by ericeslinger** [localForage/localForage#631]
All I need to do is `import localforage from 'localforage'` in a node.js package to generate an error (no available storage found) - I don't have to config localforage or anything. The error itself is in a rejected, and uncaught, promise. The problem is that in future Node.js versions, a rejected promise may end up in the process terminating with a nonzero exit code.

My situation in particular is that I'm not actually using localforage, I'm just importing a package that can be configured to use it. With ES6 style import/export code, it's unclear how one would conditionally import stuff (vs require-style imports, which can happen inside an if-else block).

Ideally, the config stuff that throws this error would be moved into an initialize method or something, instead of [returning a new LocalForage()](https://github.com/localForage/localForage/blob/2f887aa69fcea10d409fc755c208ae0363a64190/src/localforage.js#L383) from the export command.

**Comment by thgreasi** [comment]
I have already asked this in other issues disgusting the same issue, but let me repeat it one more time hoping that I will get an answer this time.
Does adding a `localforage.ready().catch(function(){})` make the error disappear?

Since localforage officially supports and primarily targets browsers, it's doing some async initialization stuff when loaded, in order to collect which drivers are available up front and prepare the default instance.

**Comment by thgreasi** [comment]
A more extreme example would be importing jQuery in node and expecting the `$(document).ready()` method not to throw (which also does some things automatically under the hood).
If adding a `.catch()` solves it for you, we should probably add a note in README.
Of course things might chance in the future, despite the benefits that automatic initialization offers to localforage, but obviously that would be a breaking change.

**Comment by thgreasi** [comment]
I have an idea...
On second, third, fourth, 99nth thought, this might be easier.
Expect a PR tomorrow or during the weekend.
I will need your feedback on that of course.

**Comment by ericeslinger** [comment]
Putting a catch on localforage.ready() doesn't help. I don't even need to call .ready() to generate the rejection error. That's because the init code that gets called in new LocalForage() is what generates the error, and there's a constructor call in the export at the end of the LF definition file.

This might be lousy for programmer ergonomics, but basically putting all the init inside a .initialize() kind of call would be good - but then frontend people have to remember to .initialize() before using localforage.

Of course, one could do a curry thing where any access method checks to see if the init has been run, and runs it. The problem, of course, is that the init code is async, so you'd have race conditions and stuff to avoid (don't run it twice!).

**Comment by thgreasi** [comment]
Got it! Running `require('localforage')` on node v6.9 no longer gives the warning.
I will open a PR later today.

**Comment by thgreasi** [comment]
Tada! Can you give a try to the code found in PR #633 ???
If it works for you, we can merge it and schedule it for the next release.

**Comment by ericeslinger** [comment]
Works for me.

**Comment by thgreasi** [comment]
Great!

**Comment by thgreasi** [comment]
Fixed by #633 planned to be released as v1.5
