### ISSUE TITLE
Support for Persistent Storage API

### ISSUE THREAD

**Issue by jmalonzo** [localForage/localForage#635]
Chrome 55 supports the [Persistent Storage API](https://developers.google.com/web/updates/2016/06/persistent-storage). I'm wondering if that's something this project can support as well?

Thanks

**Comment by tofumatt** [comment]
We do support custom drivers, so someone could write a driver that used
that storage engine as the back end. If persistent storage became a
standard across browsers and the driver was good we could see about
integrating it into the core library, but our custom driver API should be
enough for now.

- Matthew Riley MacPherson | tofumatt.com

**Comment by thgreasi** [comment]
For reference, I'm posting the [StorageManager.persist() docs mage from mdn](https://developer.mozilla.org/en-US/docs/Web/API/StorageManager/persist) as well.

**Comment by simon04** [comment]
For reference, Firefox goes with a `storage` attribute on the option object to the `open()` function: https://developer.mozilla.org/en-US/docs/Web/API/IndexedDB_API/Browser_storage_limits_and_eviction_criteria
```js
var request = indexedDB.open("myDatabase", { version: 1, storage: "persistent" });
// vs.
var request = indexedDB.open("myDatabase", { version: 1, storage: "temporary" });
```

**Comment by thgreasi** [comment]
https://blog.nightly.mozilla.org/2017/07/17/preview-storage-api-in-firefox-nightly/

**Comment by johannesjo** [comment]
Any news on this yet? Not really sure about this. Is calling
```
      navigator.storage.persist().then(...);
``` 
Enough to enable persistent storage for the whole domain?
