### ISSUE TITLE
[discussion] extra things to include in v1.5

### ISSUE THREAD

**Issue by thgreasi** [localForage/localForage#644]
* [x] <del>implement dropInstance() method #620 (suggested by @stkao05, opened by @jlchereau)</del> (moved to 1.6)

**Comment by thgreasi** [comment]
@tofumatt  please suggests any extra features to add or issues to close before releasing v1.5 .

**Comment by stkao05** [comment]
Hi @thgreasi 
Currently there is `localForage.clean()` method which remove all records of DB, but it would be nice to offer a way to complete destroy the DB, something like `localForage.deleteDatabase()`.

https://developer.mozilla.org/en-US/docs/Web/API/IDBFactory/deleteDatabase

Thanks!

**Comment by thgreasi** [comment]
@stkao05 great! For reference, dropInstance is currently reached in #620

**Comment by thgreasi** [comment]
@stkao05 to be honest I hoped v1.5 would be out before this (since after some investigation it looks non-trivial). @tofumatt any thoughts?

**Comment by tofumatt** [comment]
I'm just going through our open PRs right now and merging anything I think should be in `1.5`.

**Comment by tofumatt** [comment]
I can't think of anything in particular, so I'll update this issue once I'm done checking. I think `dropInstance` might be a better fit for 1.6 if it's not trivial, which it sounds like it's not.

**Comment by pjjackowski** [comment]
Would it be feasible to add `instances()` to get the list of all datastores, like `keys()` gets the list of all keys in the given datastore? I may be missing something, but I can't see any way to do it right now.

**Comment by tofumatt** [comment]
We’d need to keep track of the names of the DBs, which I think right now we don’t. I could certainly see us storing said info in a _localForage DB (or wherever we store “hidden” data already in IndexedDB feature tests we run at first).

I’m open to the feature, but we’d need to add info about which DBs are in use.
