### ISSUE TITLE
Error on example page (jsfiddle) 

### ISSUE THREAD

**Issue by jayasenthilceg** [localForage/localForage#646]
localforage.min.js is missing on jsfiddle. PFA for reference.

<img width="1271" alt="screen shot 2017-01-19 at 12 42 39 pm" src="https://cloud.githubusercontent.com/assets/4212700/22097019/d037dada-de44-11e6-9a91-d6ac80efa74e.png">
<img width="1271" alt="screen shot 2017-01-19 at 12 42 22 pm" src="https://cloud.githubusercontent.com/assets/4212700/22097020/d03c97dc-de44-11e6-9bc7-4d821c989469.png">

**Comment by thgreasi** [comment]
Nice catch 👍 
Thanks for reporting.
Fixed with d9cbb37c28d3b8a689e1388b178e494c0c4ecd8c
