### ISSUE TITLE
Changing Firefox settings causes uncatchable exceptions

### ISSUE THREAD

**Issue by AshleyScirra** [localForage/localForage#647]
In Firefox, go to Options -> Privacy -> History and set Firefox to "Never remember history".

Now all localforage calls throw uncatchable exceptions. Demo URL: https://www.scirra.com/labs/bugs/localforage-crash/

This calls `localforage.getItem()` inside a try-catch block and it still throws an unhandled exception. Presumably there's an internal callback that ends up throwing an exception.

IMO this behavior of Firefox is really annoying, since it breaks pages and libraries that haven't been tested specifically with this particular Firefox setting. It also results in bug reports in our software (https://www.scirra.com/forum/localstorage-crash-with-firefox-no-history_t186255). It's not clear what we can do about this simply as a consumer of the library, because there's no way to catch the exception that is thrown. So I think libraries like localforage ought to handle this to hide these quirks from library users.

This is also precisely why I think there ought to be a memory fallback as proposed in PR #555.

**Comment by tofumatt** [comment]
While this bug makes me more likely to include an in-memory fallback, it
also seems like a browser bug we should file. I’ll check into that.

I used to worry about not erroring when we aren’t successfully storing the
data, but I guess in this case we aren’t either way. We should definitely
have prominent logging when in-memory is used, but I think this increases
usability and is a good idea.

**Comment by thgreasi** [comment]
It seems browser weird magic to me as well. I can confirm that I couldn't find a way to catch the error and reject properly. The error appears on FF private browsing, [localforage fall backs to using localstorage and data are properly stored and retrieved](http://codepen.io/anon/pen/WRpZQo).

**Comment by thgreasi** [comment]
I could open a new PR with the memory storage driver currently available under the localforage organization.
BUT
*  as you can see on the provided example, localforage continues to work and properly stores and retrieved data from localstorage ... so I guess the error message logged isn't actually "breaking the page" (tested on Private Browsing + Never Remember History).
* others have mentioned in other issues that are in favor of making localforage pluggable and as slim as possible

Waiting for your feedback.

**Comment by thgreasi** [comment]
An other statement against embedign a memorystorage driver was that:
in order to be sure that the data are saved you will have to check both whether the promise actually resolved but also check the driver that is currently used.

**Comment by AshleyScirra** [comment]
Checking the driver, or waiting for a promise to resolve, doesn't actually tell you if storage was really permanently saved. In Chrome Incognito mode, all IndexedDB calls will succeed, even though it's effectively using memory storage. Even in normal browsing mode, there's no guarantee the browser won't suddenly decide to do a cleanup and trim its disk space usage, and delete all your site's saved content. (Or the user could do it.)

The only way to be sure that storage will persist is to call [navigator.storage.persist()](https://developer.mozilla.org/en-US/docs/Web/API/StorageManager/persist), which is not yet widely supported but is the only way to reliably find out the answer to the question "will my storage actually be kept?"

Also given the minified + compressed size of localforage is about 8kb, I'm not sure why anybody is worried about the size of the library. You could double it and nobody would notice.

**Comment by thgreasi** [comment]
Adding a `e.preventDefault();` call inside the `indexedDB.open().onerror()` handler seems to prevent the error from reaching `window.onerror()`. [Sample codepen](http://codepen.io/anon/pen/RKVMQp?editors=0010). Any chance this might have other side effects?

**Comment by thgreasi** [comment]
@AshleyScirra thanks for your commitment on this so far.
I just opened PR #648 that possibly resolves this.
As soon as you can confirm that this works for you, we can merge it in for v1.5 .

**Comment by thgreasi** [comment]
[Here is a fork of the original codepen using the code from PR 648](http://codepen.io/thgreasi/pen/ZLyzqr).
Still works on Chrome (+ Private Browsing) and the Error no longer shows up on FF Privare Browsing.

**Comment by AshleyScirra** [comment]
Tested PR #648 in Construct 2 in Firefox stable and nightly with the "never remember history" setting. It no longer throws the uncatchable error. Looks like it's sorted.

**Comment by thgreasi** [comment]
Great!
