### ISSUE TITLE
WARNINT in ./~/.npminstall/localforage/1.4.3/localforage/dist/localforage.js  pre-built

### ISSUE THREAD

**Issue by aeolusheath** [localForage/localForage#649]
```
Critical dependencies:
7:484-491 This seems to be a pre-built javascript file. Though this is possible, it's not recommended. Try to require the original source to get better results.
 @ ./~/.npminstall/localforage/1.4.3/localforage/dist/localforage.js 7:484-491
```
I have seen the three similar issues ,  use noParse ,
```
    noParse: [new RegExp('node_modules/localforage/1.4.3/localforage/dist/localforage.js')]
```
or

```
 noParse: [new RegExp('node_modules/localforage/dist/localforage.js')]
```
but  did not work for me ,

please help

node version: 4.4.7

localforage version: 1.4.3

**Comment by thgreasi** [comment]
Have you tried the expression found in readme?

**Comment by aeolusheath** [comment]
@thgreasi   https://github.com/localForage/localForage#browserify-and-webpack this text?

I read it , and I modify the config of webpack but the warning still exist

**Comment by thgreasi** [comment]
Did you try modifying it to match the path from your warning?
> .npminstall/localforage/1.4.3/localforage/dist/localforage.js

**Comment by aeolusheath** [comment]
@thgreasi   it works. thanks for your time, bro...

**Comment by heygrady** [comment]
The readme has a typo. This worked for me: `noParse: /.*\/localForage\/dist\/localforage\.js/`

Also, Webpack is very popular. It's odd for a library to demand that users add a special exception their configs when nearly every other library *just works*.

**Comment by tofumatt** [comment]
> Also, Webpack is very popular. It's odd for a library to demand that users add a special exception their configs when nearly every other library just works.

I totally agree; it's something we have to work on and are planning to tackle in future releases 👍
