### ISSUE TITLE
Indexeddb support in Safari 10.1+

### ISSUE THREAD

**Issue by dennismartensson** [localForage/localForage#650]
Safari 10.1 [has shipped](https://developer.apple.com/library/prerelease/content/releasenotes/General/WhatsNewInSafari/Articles/Safari_10_1.html) with full and performant support for IndexedDB according to [this](https://github.com/pouchdb/pouchdb/pull/6173) PR over at pouchdb.

I think we should get this to localForage.

**Comment by tofumatt** [comment]
Agreed, sounds good 👍🏻

**Comment by dennismartensson** [comment]
Thinking that [this changes](https://github.com/pouchdb/pouchdb/pull/6173/files?diff=split) are the same as the ones we should do to [utils/isIndexedDBValid.js#L19](https://github.com/localForage/localForage/blob/2796ccd7898fc92adf57acbbf31028728bce23fd/src/utils/isIndexedDBValid.js#L19)

**Comment by thgreasi** [comment]
I can merge nolanlawson's changes to localforage, it shouldn't be a big
deal. My only concern is that I won't be able to do any testing since I
currently don't have any iOS device available.

> --
*Thodoris Greasidis*

**Comment by tofumatt** [comment]
I can test them, but if it's working for PouchDB I think it should work for us.

**Comment by dennismartensson** [comment]
Have a PR here #651

**Comment by thgreasi** [comment]
Resolved by #651

**Comment by Narcwis** [comment]
I tested [this jsfiddle](https://jsfiddle.net/euhejqvh/) on Safari 10.2. The main page uses localstorage but when I open the result frame in a new tab it uses asyncstorage. Feel free to create codepen or jsfiddle for me test, I will be more than happy to contribute.

**Comment by thgreasi** [comment]
@Narcwis `asyncstorage` stands for IndexedDB, so your results are indicate that #651 works and this is resolved.
It seems that the safari + iframe => localstorage issue is not something we can do something for.
Thanks for your feedback confirming that this works!
