### ISSUE TITLE
Webpack 2: Error: No available storage method found

### ISSUE THREAD

**Issue by ngocketit** [localForage/localForage#653]
I'm trying to use localForage with Webpack 2.2.0, node 7 and got this error: `UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): Error: No available storage method found`. The code is just a very simple import:
```
import localForage from 'localforage';
```

I didn't get the warning about pre-built as many did. Any ideas?

**Comment by pvanngoc** [comment]
This seems to be related to this: [#626](https://github.com/localForage/localForage/issues/626) but the fix is not included in current version yet. When are you planning to release 1.5?

**Comment by thgreasi** [comment]
Yes that's exactly what #626 was mentioning and is resolved in the current master with #633.
I hope we can cut a new release soon.
