### ISSUE TITLE
Add notice about v1.5 and the data of existing Safari users

### ISSUE THREAD

**Issue by thgreasi** [localForage/localForage#655]
As a result of enabling IndexedDB for Saferi v10.1+ #651, we should probably add a notice that after upgrading to v1.5, existing Safari 10 users will not be able to find their data. We could probably add a link to an issue suggesting a way to detect and migrate their data from WebSQL to IndexedDB.

**Comment by tylergraf** [comment]
@thgreasi When do you plan to release 1.5?

**Comment by tylergraf** [comment]
Will you be creating pre-releases?

**Comment by thgreasi** [comment]
I will be more than happy to review a PR for this. Otherwise will try to find some time until the end of this week. I think that we are ready for v1.5.

**Comment by tylergraf** [comment]
@thgreasi I made a PR here: https://github.com/localForage/localForage/pull/661

**Comment by thgreasi** [comment]
Closed by #662
