### ISSUE TITLE
localforage.createInstance: unable to read data set in create instance

### ISSUE THREAD

**Issue by Eccenux** [localForage/localForage#671]
**Steps**:
1. Create LF instance.
2. Set some data.
3. Attempt to load data.

**Result**: value of the data is `null`.
Also note that when you you look in the Dev Tool the data is actually set. It seems like localforage can't read this.

**LF version**: 1.5.0
**Browsers tested:** FF 51, Chrome 56 / 57.

**Test case without reload**
(just run this on page load)
```js
var testStore = localforage.createInstance({
	name: 'test'
});
testStore.setItem('someItem', '123', function(){
	testStore.getItem('someItem', function(value){
		console.log(value); // MUST not be null
	});
});
```
**Test case with reload**
(just run this on page load)
```js
var testStore = localforage.createInstance({
	name: 'test'
});
if (location.hash !== '#set') {
	testStore.setItem('someItem', '123');
	location.hash = '#set';
	location.reload();
}
else {
	testStore.getItem('someItem', function(value){
		console.log(value); // MUST not be null
	});
}
```

**Comment by tofumatt** [comment]
I just checked and there is definitely a bug here, it seems to be specific to callbacks.

The Promises code path will work fine:

```js
testStore.getItem('someItem').then(function(value) {
  console.log(value); // will output the correct value
});
```

That's not good, I'll look to fix it (though in version 2.0 I suspect we'll be ditching callback support, it should still work now).

In the interim promises will work; we'll have to check this out and release a fix. 😮

**Comment by Eccenux** [comment]
Oh... I've re-written and noticed `getItem` callback has different parameters. The first parameter is `error` and `value` is in second. Ups.

So everything is fine. Sorry and thanks :-).

**Comment by tofumatt** [comment]
Hahah you're right and I just copy+pasted the code without thinking. Oops, my bad too! Thanks for catching that, I was wondering how our tests didn't catch this bug 😉

Thanks 👍
