### ISSUE TITLE
cannot find 'localforage'

### ISSUE THREAD

**Issue by aaawhz** [localForage/localForage#675]
when i use the demo  in local test , 'localforage' has been defined,  but on the server , 'localforage' is not defined..

using  <script src="..localforage.js" /> , 

the net work has returned to the localforage.js

**Comment by aaawhz** [comment]
module.exports = localforage_js;

//update localforage.js , add the following line,  the problem resolved 
window.localforage = localforage_js

**Comment by tofumatt** [comment]
Are you trying to use localForage in node? localForage is a browser library only.

**Comment by aaawhz** [comment]
just in browser

**Comment by tofumatt** [comment]
Which demo page are you trying to use?

**Comment by aaawhz** [comment]
localForage-master \localForage-master\examples\index.html

**Comment by thgreasi** [comment]
I'm still not getting how you are trying to use localforage. Running index.html simply with a double click on the file works (logs appear in the console) on both Firefox and chrome.

**Comment by thgreasi** [comment]
Closing this for now.
Please take a look at #624 and the live example we added in README.
Feel free to re-open in any case.
