### ISSUE TITLE
hash feature

### ISSUE THREAD

**Issue by 3luyka** [localForage/localForage#677]
Hello everyone,

How about provide feature like `hash` (e.g. base64) before saving data to storage? It would be very helpful for SPA application. (Because saving "open" user (and not only user) data in storage not safe).

What do you think about it?

**Comment by tofumatt** [comment]
base64 isn't really a hashing feature; it obscures the content but it is easily converted back (it's not a one-way hash) so it won't really be secure. You can base64 encode any content and put it in localForage, but that's outside the scope of localForage.

But that won't make the content secure; a user could look at it and base64decode it easily. If you want to store data that the user can't decrypt you'll want one-way encryption... or maybe to look at JS encryption (which I don't know much about).
