### ISSUE TITLE
LocalForage 1.4.3 : Firefox 52_0_1 : Private Mode

### ISSUE THREAD

**Issue by ZhnZhn** [localForage/localForage#678]
On call LocalForage 1.4.3 : Firefox 52_0_1 : Only in Private Mode
LocalForage.getItem(KEY)
                .then()
                .catch()

in console InvalidStateError  from indexeddb.js (line 135)

function _getConnection(dbInfo, upgradeNeeded) {
            return new Promise$1(function (resolve, reject) {
              if (dbInfo.db) {
                if (upgradeNeeded) {
                  _deferReadiness(dbInfo);
                  dbInfo.db.close();
                } else {
                  return resolve(dbInfo.db);
                }
              }
              var dbArgs = [dbInfo.name];
              if (upgradeNeeded) {
                dbArgs.push(dbInfo.version);
              }
              var openreq = idb.open.apply(idb, dbArgs); // on this line
     
It's not critical, all seems works as expected only a uncatched error message in a console.

**Comment by tofumatt** [comment]
Yes, this is a known issue. Unfortunately offline storage generally does not work well in private browsing mode on many browsers.

**Comment by thgreasi** [comment]
Can you try v1.5? I think that we more prevent the error to bubble and
reach the window.

> --
*Thodoris Greasidis*

**Comment by ZhnZhn** [comment]
Yes, I can try v1.5 but not now. Thanks.
