### ISSUE TITLE
Add memoryStorageDriver

### ISSUE THREAD

**Issue by thgreasi** [localForage/localForage#681]
As mentioned in #145 .
Initial PR #555

**Comment by NickGeek** [comment]
Is there any update on when this will be done?

**Comment by tofumatt** [comment]
None yet, but I hope over the holidays I can help out with our 2.0 release. It will hopefully ship sometime late December or early January if we get the time.

- Matt (Sent from mobile)

**Comment by thgreasi** [comment]
@NickGeek #721 is the PR to keep an eye on.

**Comment by thgreasi** [comment]
A memory storage driver was added to the v2.0-dev branch with 40c70210a54645c33919a283b2a1138f40b7a001.
