### ISSUE TITLE
Angular 4.0 support

### ISSUE THREAD

**Issue by HartHerbert** [localForage/localForage#684]
Since I updated to Angular 4.0 I get multiple errors in the cli

### Error1
` typescript: C:/Development/Pookypet/node_modules/@types/localforage/index.d.ts, line: 7
            Subsequent variable declarations must have the same type. Variable 'driver' must be of type 'string |
            string[]', but here has type 'string | LocalForageDriver | LocalForageDriver[]'.
`
### Error2
`typescript: C:/Development/Pookypet/node_modules/@types/localforage/index.d.ts, line: 15
            Subsequent variable declarations must have the same type. Variable 'version' must be of type 'number', but
            here has type 'string'.`
### Error3
`
typescript: C:/Development/Pookypet/node_modules/@types/localforage/index.d.ts, line: 25
      L16:      _driver: string;
            Subsequent variable declarations must have the same type. Variable '_support' must be of type 'boolean |  LocalForageDriverSupportFunc', but here has type 'boolean | Promise<boolean>'.`
### Error4
`typescript: C:/Development/Pookypet/node_modules/@types/localforage/index.d.ts, line: 25
            All declarations of '_support' must have identical modifiers.
      L24:      getItem(key: string, callback: (err: any, value: any) => void): void;
      L26:      key(keyIndex: number, callback: (err: any, key: string) => void): void;`
### Error5
` typescript: C:/Development/Pookypet/node_modules/@types/localforage/index.d.ts, line: 100
            Duplicate identifier 'export='.
`

### Error6
`typescript: C:/Development/Pookypet/node_modules/localforage/typings/localforage.d.ts, line: 47
            Interface 'LocalForageDriver' incorrectly extends interface 'LocalForageDbMethods'. Types of property  'getItem' are incompatible. Type '(key: string, callback: (err: any, value: any) => void) => void' is not  assignable to type '{ <T>(key: string): Promise<T>; <T>(key: string, callback: (err: any, value: T) =>
            void): void; }'.`

### Error7
`typescript: C:/Development/Pookypet/node_modules/localforage/typings/localforage.d.ts, line: 113
            Duplicate identifier 'export='.
 export = localforage;`

Any help?

**Comment by tofumatt** [comment]
Which version of localForage are you using? We recently changed how we do TypeScript so the docs for the latest version (https://github.com/localForage/localForage#typescript) might help.

**Comment by HartHerbert** [comment]
I'm using Localforage version `1.5.0` and the `@types/localforage` is version `0.0.30` and I'm importing localforage like this 
``` typescript
import localforage from "localforage";
```

**Comment by thgreasi** [comment]
As noted in #680
> As with localforage v1.5 you no longer need to user @types definition of localforage, since they are now part of the library itself. Just delete the node_modules/@types/localforage/ folder and you will be ready to go.

Can you confirm that this works for your case?

**Comment by HartHerbert** [comment]
worked just fine! Thanks
