### ISSUE TITLE
defineDriver's API introduces the need for ready event

### ISSUE THREAD

**Issue by gabrielmaldi** [localForage/localForage#686]
The docs state that:

> You don’t need to run any init method or wait for any `onready` events.

And this is great.

However, when using a custom driver like this:

```js
localforage.defineDriver(myDriver);

localforage.createInstance({
  driver: myDriver._driver
});
```

I get:

<img width="456" alt="screen shot 2017-04-11 at 7 08 29 pm" src="https://cloud.githubusercontent.com/assets/3728897/24932959/489bfab6-1eea-11e7-885a-12d084b054ce.png">

So, instead, I need to use:

```js
localforage.defineDriver(myDriver).then(function () {
  localforage.createInstance({
    driver: myDriver._driver
  });
});
```

In any nontrivial app, a component will need to call `getItem` (or `setItem`, etc.) on a store; but when using a custom driver, it will first need to wait for the instance to be created. So, we are forced to make the module which creates the stores expose a `ready` event/promise, which components wait for before reading/writing to stores.

Would it be possible to remove this limitation from `defineDriver`'s API and just have it queue up tasks the same way everything else in `localForage` works?

Thanks

**Comment by thgreasi** [comment]
We could define the driver syncronously but we need the result of the `_support()` method of the custom driver, which might be a promise. We complete the driver setup right after the result of the `_support()` method gets resolved. It could be probably feasible to change the code to the setup drivers differently, based on existence (or not) of the `_support()` method and it's return type.

**Comment by gabrielmaldi** [comment]
Thanks for your answer. I opened #692 to work on this.
