### ISSUE TITLE
Remove instance on IndexedDB

### ISSUE THREAD

**Issue by LeonardoCiaccio** [localForage/localForage#688]
How i can remove this with code ?

![screenshot-jsfiddle net 2017-04-25 14-37-01](https://cloud.githubusercontent.com/assets/1698144/25385576/d25ecf14-29c4-11e7-9ff9-877d1171bc13.png)

**Comment by thgreasi** [comment]
Localforage doesn't provide an API for such operations at the moment.
You should use the WebSQL API directly.
I'm closing this for now and point you to #620 where we are tracking the progress for such an API.
Feel free to re-open in any case.

**Comment by thgreasi** [comment]
@LeonardoCiaccio  The `dropInstance()` PR in in the current master (and planned to be released as LF v1.6) can you give it a try?
