### ISSUE TITLE
License not clear.

### ISSUE THREAD

**Issue by nisimjoseph** [localForage/localForage#696]
hi,

I want to use that library in my project but I can't because of the license. is it in purpose or default of GitHub?
can you make it "MIT" or "apache license version 2.0" ?

thank you,
Nisim

**Comment by thgreasi** [comment]
The [LICENSE](https://github.com/localForage/localForage/blob/master/LICENSE) file says `Licensed under the Apache License, Version 2.0`.
Isn't that ok for you?

**Comment by nisimjoseph** [comment]
for me it not an issue, for the startup I am working for it not ok.
usually you have those types: https://choosealicense.com/

so it clear what it mean. github also show it nice with what can and can't do.
+ I know MIT is more freely, so usually they want here MIT license.

**Comment by thgreasi** [comment]
So,
1. Is the license clear `Licensed under the Apache License, Version 2.0`?
2. Should we close this?
3. Is this a request to change this library's license?

**Comment by nisimjoseph** [comment]
1. it clear.
2. you can. we don't have issue with standard Apache License 2.0.
3. not need if it too much work. but MIT is better.

thank you,
Nisim
