### ISSUE TITLE
[Feature] add method similar to getItem, but also removes the item

### ISSUE THREAD

**Issue by raniesantos** [localForage/localForage#697]
Add a method that would get an item's value and also remove it.

Here's a rough example of what I mean:

```js
flashItem(key) {
	let item = localStorage.getItem(key);
	localStorage.removeItem(key);
	return item;
}
```

**Comment by tofumatt** [comment]
I don't see a common use case for such a method and it would add bloat to the library.

It should be easy for you to create your own method that does this.

Please read the [localForage API](https://localforage.github.io/localForage/#data-api-getitem) though, your example is synchonous so it won't work; localForage's API is async.
