### ISSUE TITLE
How to add data to specific storeName?

### ISSUE THREAD

**Issue by AUSdomgarcia** [localForage/localForage#700]
set, get seems a practice when using local storage and session storage. But i want to use WebSql driver. I became limited to add and found some difficulties on getting data through that way/system. Can you give me an example on how to properly add data in a "storeName"( or table like) using LocalForage?

**Comment by thgreasi** [comment]
Hi there.
You should either use the [`config()`](https://localforage.github.io/localForage/#settings-api-config) method to set the storeName for your default LF instance, or use [`createInstance()`](https://localforage.github.io/localForage/#multiple-instances-createinstance) (which accepts all the options as `config()`) and create a new LF instance to manage the specific storeName.
Closing this for now. Feel free to re-open in any case.

**Comment by AUSdomgarcia** [comment]
Im using Typescript, following steps here https://ionicframework.com/docs/storage/
when i use this I am limited to utilize method of LF for not declare in typescript. I can only setup once here
`
IonicModule.forRoot(MyApp),
    IonicStorageModule.forRoot({
      name: 'mydb',
      storeName: 'users',
      driverOrder: ['sqlite', 'websql']
    })
`
how will I manage this?

**Comment by thgreasi** [comment]
In that case I think you will have to ask from Ionic-storage to also expose the `createInstance()` method.
PS: I'm not fully aware of the Ionic-storage API

**Comment by AUSdomgarcia** [comment]
Really?
I thought you guys have collaborated closely to each other. 

anyways, thanks man!

**Comment by thgreasi** [comment]
Actually it seems that `forRoot()` leads to the constructions of a new `Store` object, which leads to a call to the `createInstance()` method. So, you might be able to use multiple `IonicStorageModule.forRoot({})` calls and get the respective store objects.
Hope this helps!

**Comment by thgreasi** [comment]
PS: [StorageConfig](https://github.com/ionic-team/ionic-storage/blob/master/src/storage.ts#L233-L237) has a storeName property
