### ISSUE TITLE
Weird driver switch between initial visit and after refresh web page

### ISSUE THREAD

**Issue by gnhuy91** [localForage/localForage#701]
I am not sure if this is a bug, would be great someone can help me confirm this.

Tested on Chrome `58.0.3029.110`.

I am using React, on my `src/index.js`, before `ReactDOM.render`, I config `localForage`:

```js
localForage.config({
  driver: [localForage.INDEXEDDB, localForage.LOCALSTORAGE],
  name: 'MyApp',
  version: 1.0,
  description: '',
});

localForage.ready().then(() => {
  console.log(localForage.driver());
});
```

- On initial page visit, .ie **open a new tab** and type `localhost:3000`, above log result was `asyncStorage`.
- When **I refresh the current tab**, log result was `localStorageWrapper`.

**Comment by tofumatt** [comment]
That's strange; is there any chance you have a race condition or are making a different call to localForage before your config call? Could you post a more full code snippet to see the code in context?

**Comment by gnhuy91** [comment]
`src/index.js`

```
...

// localForage config
localForage.config({
  driver: [localForage.INDEXEDDB, localForage.LOCALSTORAGE],
  name: 'MyApp',
  version: 1.0,
  description: '',
});

localForage.ready().then(() => {
  console.log(localForage.driver());
});

// render
ReactDOM.render(
  <Provider store={store}>
    <AppContainer>
      <Router />
    </AppContainer>
  </Provider>,
  document.getElementById('root'),
);

// register service worker
registerServiceWorker();
```

**Comment by tofumatt** [comment]
If you leave out the `config()` call does anything change?

**Comment by gnhuy91** [comment]
when I commented out `config()`, it always log `localStorageWrapper` regardless.

**Comment by tofumatt** [comment]
That's very strange! Do you have any add-ons on the browser or something messing with `IndexedDB`? What version of localForage are you using? It should be `asyncStorage` by default...

**Comment by gnhuy91** [comment]
I'm using localforage `1.5.0`. Let me try in private mode.

**Comment by gnhuy91** [comment]
Great, on private mode it always `asyncStorage`, must be some of my extension...

**Comment by tofumatt** [comment]
Private mode will always force localStorage because private mode has bad IndexedDB and WebSQL support.

**Comment by gnhuy91** [comment]
thats even weirder, my private Chrome mode always log `asyncStorage`.

**Comment by gnhuy91** [comment]
By the way just auto updated to Chrome 59.

**Comment by tofumatt** [comment]
That's strange, but it sounds like it might be something on your Chrome install. If you can replicate this on another browser or machine, please re-open.

If you find out what this was please comment and let us know 😄

**Comment by gnhuy91** [comment]
Thanks for your help!

**Comment by gnhuy91** [comment]
Found it, so after disabling all extensions and enable them one by one, as soon as I enable `Last Pass` extension and visit my web page - it logs `localStorageWrapper`, so disabling it for now.

**Comment by tofumatt** [comment]
Wow, and that’s a very popular extension. Good to know, I’ll remember that if we run into this in the future! Thanks!

**Comment by thgreasi** [comment]
An out of scope comment from me: :+1: for using `ready ()`
