### ISSUE TITLE
Huge WAL File

### ISSUE THREAD

**Issue by SteveBrooker** [localForage/localForage#702]
I have been using localForage for IOS App development for the past 3-4 years very successfully but recently I have noticed that over time the App Size increases dramatically and I have found that this is caused by the SQlite Write Ahead Logging (WAL) file continually growing. I do not know if this also slows down performance but I do know that what should take 30MBytes of memory on the phone is eventually taking 2+GBytes.
It would help if it was possible to define SQLITE PRAGMA parameters from within localForage when it created the database so that I could try non WAL mode.

**Comment by tofumatt** [comment]
A quick Google search seems to indicate issung `PRAGMA` commands to WebSQL is not supported, unfortunately. This is unfortunate but it seems this is an issue with iOS and not localForage directly. I'm surprised that file isn't cleaned somehow, but unfortunately there isn't a way for us to modify this behaviour from our end. Sorry about that! 😞

**Comment by boedy** [comment]
Our team is experiencing the same issue. It occurs when replacing existing keys. We suspect this bug was introduced in iOS 10.3. By first removing a key before writing this problem can be circumvented. It's hacky, but we currently resolve it that way, until there is a fix.

**Here a code snippet to reproduce the bug**
```js
var dummyData = [];
for(var i = 0; i < 100000; i++){
  var dummyEntry = {firstName: 'John', lastName: 'Doe', email: 'john@example.com' }
  dummyData.push(dummyEntry);
}

//this will cause the wall file to grow
var interval = setInterval(overwriteData, 100);

//by deleting they key before writing the wall file will not grow
//var interval = setInterval(removeInsertData, 100);


function overwriteData() {
    localforage.setItem('data', dummyData).then(function (value) {
      console.log('Data has been saved');
    }).catch(function(err) {
      console.log(err);
    });
}

function removeInsertData() {
  localforage.removeItem('data').then(function (value) {
    console.log('Data has been removed');
    localforage.setItem('data', dummyData).then(function (value) {
      console.log('Data has been saved');
    }).catch(function(err) {
      console.log(err);
    });
  }).catch(function(err) {
    console.log(err);
  });
}
```
