### ISSUE TITLE
Firefox Storage API

### ISSUE THREAD

**Issue by YuriyPobezhymov** [localForage/localForage#703]
Hello.
I found you interesting library.
I know that there are small amount of browsers that support Web SQL - so it's cool that you library has possibility to enable it if available.
Firefox supports IndexedDB, not Web SQL.
But what I found - they have support [Storage API](https://developer.mozilla.org/en-US/docs/Mozilla/Tech/XPCOM/Storage) for extensions and Firefox components only.
I don't know if it has comparable speed to Web SQL. May somebody knows?
Is it complicated thing to add support for that one in you library and is it reasonable thing?

Thanks, Yuriy.

**Comment by thgreasi** [comment]
Hi there!
I think that support for that storage method should be implemented as a custom driver, like the [localforage-cordovaSQLiteDriver](https://github.com/thgreasi/localForage-cordovaSQLiteDriver), since this library is primarily focused on storage methods that browsers have available to web pages.

**Comment by tofumatt** [comment]
That storage API is legacy and not really intended for web pages or extensions to use... I wish I could find the bug where it was discussed but I recall a few years back us encouraging developers using it to switch their extensions over to localForage actually 😄

IndexedDB should give you speeds similar to WebSQL, the Storage API is not, as I recall, especially fast.

As mentioned you could implement it with a custom driver if you want, but it won't be something that would be a good fit for localForage or for any cross-platform pages. I'd encourage you to use localForage as-is instead 😄

**Comment by YuriyPobezhymov** [comment]
Thank you for information!
