### ISSUE TITLE
LocalForage: IndexDB Size Requirements

### ISSUE THREAD

**Issue by Moonwalker7** [localForage/localForage#707]
My application will be caching data in the range of 150-200 Mbs.

Will Localforage cache this much of data using indexDB ?
Also i need to cache videos and images, should i cache it using localForage or it should be done through some other way ?

**Comment by tofumatt** [comment]
You can certainly use localForage to store large amounts of data. That should be fine using IndexedDB. If you're storing large files you might find memory usage is a bit high but it should be no problem as long as you're using IndexedDB.
