### ISSUE TITLE
Fallback to another storage method when localStorage isn't available

### ISSUE THREAD

**Issue by jesusbotella** [localForage/localForage#715]
Hello,

We are currently using localForage in our PWA by means of ionic storage, we are really happy :)

We are facing an issue with Safari and localStorage in private browsing mode (as many other people) when trying to save data. It throws an error and it doesn't use any other fallback because it treats the error as if something wrong happened instead of "this storage method is not available". Private navigation in browsers, when it comes to storage, is not a pretty good thing as you already know.

I think that the issue is that localForage's [localStorage supports function](https://github.com/localForage/localForage/blob/master/src/utils/isLocalStorageValid.js), and [localStorage driver's _initStorage function](https://github.com/localForage/localForage/blob/master/src/drivers/localstorage.js#L11) determine that localStorage is available when it is actually not letting save anything. I think that it could be solved by checking if it is actually saving data, and not throwing a quota error, in any of these methods.

It would be really useful when having a localStorage fallback method like in-memory storage because if it is not checked it wouldn't be used at all.

That said, I'd be happy about solving it in a PR if you agree that this is the way to go with this issue.

Thank you!

**Comment by tofumatt** [comment]
Indeed, this is a request I think we'd like to accept because the private browsing errors are not obvious and it would be better to have an in-memory fallback. I know there's #555 and https://github.com/localForage/localForage-memoryStorageDriver as a custom driver but it would be great to get this integrated. Not sure if #555 is largely ready... I could have another look maybe next week.

**Comment by thgreasi** [comment]
Adding a memory storage driver is tracked in #681 and the current milestone is for v1.6.
I will try to open a PR to integrate [memoryStorageDriver](https://github.com/localForage/localForage-memoryStorageDriver) during the weekend. I will first try to rebase #555 just for the credits, but it's a bit outdated.
I also think that this should be v2.0, since semver wise, there will be a change on the behavior of LF. There might be people expecting to catch the `no storage driver available` error on `.ready()` (even though I hope not). @tofumatt what do you think on that?

**Comment by tofumatt** [comment]
I think that’s a good point and memory storage is a good reason to bump to v2.

**Comment by jesusbotella** [comment]
Yeah, the in-memory storage thing is why I opened this issue :)

The thing is that if you are in private browsing mode, the localStorage is marked as available in supports method, and _initStorage method even though it is not true because when you try to save something throws an error.

So, even though people is expecting to catch the `no storage driver available` error in `.ready()` that wouldn't happen in private browsing because the localStorage will be ready to save data, and then when you try to do it, it will throw. So they will be missing it already.

**Comment by thgreasi** [comment]
Discussion with @jesusbotella from #723:
> I would prefer to keep the validity methods without consequences. I would prefer the test setItem call to be inside the [_initStorage](https://github.com/localForage/localForage/blob/d58233e73f6d5e4878b615a3576fcb4b6428e9b6/src/drivers/localstorage.js#L30) method, in a similar manner with what the indexeddb driver does (having a constant for the test "database" & following a similar naming schema).

> We would also need a test case for that, probably extending the [faultydriver test cases](https://github.com/localForage/localForage/blob/master/test/test.faultydriver.html) to override `localStorage` with a method that would throw an error.

@jesusbotella  Let's continue the discussion here.

**Comment by thgreasi** [comment]
Or maybe even better in an other issue if you prefer?

**Comment by jesusbotella** [comment]
No, I think it is better to follow here, isn't it? That was the purpose of the issue (check if localStorage works properly), seeing that the fallback between methods works successfully right? :)

So, I think I can do what you propose in your latest comment.
For the faulty driver test, I think the best way to test it is overriding the localStorage's `setItem` function in the index file (the same way as WebSQL openDatabase function) and throwing the error that Safari actually throws in private browsing. And then add the localStorage driver to [faulty driver test driver list](https://github.com/localForage/localForage/blob/master/test/test.faultydriver.js#L5). Am I right?

**Comment by thgreasi** [comment]
:+1:

**Comment by thgreasi** [comment]
A memory storage driver was added to the v2.0-dev branch with 40c70210a54645c33919a283b2a1138f40b7a001.
