### ISSUE TITLE
localForage (via Ionic Storage) is lying about result for driver webSQLStorage

### ISSUE THREAD

**Issue by janpio** [localForage/localForage#716]
I first posted this at the Ionic Storage repo: https://github.com/ionic-team/ionic-storage/issues/119 But as this is only a wrapper around localForage I think here might actually be the better place to talk about it. Here is my original post:

Javascript "allows" properties on arrays, because everything is an array in Javascript. Of course this only seems to work in some browsers: Chrome allows this, Firefox doesn't.

When you try to `storage.set` such an array on iOS with driver `webSQLStorage` (default for simulated iOS in Chrome browser), it will tell you that it saved the array as you gave it to the function. But if you later storage.get the key you used, you will receive and empty array `[]` back. This is confusing and a source for bugs.

On Android (device or emulated in Chrome via `ionic serve`) everything works as expected.
On iOS (emulated in Chrome via `ionic serve`) an empty array is returned from storage. 
On iOS the default driver is asyncStorage on real devices.
(Testing in Firefox  via `ionic serve` swallows the porperty from the beginning.)

I created a repo to try this at https://github.com/janpio/ionic-storage-brokenarray

Is this a problem of localForage (and so Ionic Storage) or just a Javascript mess?

**Comment by tofumatt** [comment]
If you're creating an array and setting arbitrary keys on it like:

```js
let myArray = ['foo', 'bar'];
myArray.something = 'another value';
```
and trying to store that array, I'd say it's just a JS mess. You should be using an Object instead, as Array types in JS don't support custom keys generally speaking and I'd imagine this would lead to lots of bugs.

**Comment by janpio** [comment]
Ok, fair enough.

What cost me so much time was that localForage actually reported the array was saved in its (broken) state, and only reading it back later returned the empty array `[]`.
