### ISSUE TITLE
Is it possible to get a dump of the LocalForage database?

### ISSUE THREAD

**Issue by blueelvis** [localForage/localForage#718]
I am working on a chrome extension and because of too many security limitations regarding the direct File System access, is it possible to get a dump of the localForage database for backup purposes?

**Comment by tofumatt** [comment]
Yes, in order to make a backup of the entire database you'd need to use the [`.keys()`](https://localforage.github.io/localForage/) API and then likely the https://github.com/localForage/localForage-getItems method to generate a file in JS.

**Comment by blueelvis** [comment]
Oh okay. Will write a custom one then to generate the backup in JSON . Thanks!

**Comment by thgreasi** [comment]
Also depending on the size of your db, you might not want to make a single huge operation. So keep in mind that you can get the `length()` of the items in the db and then use `iterate()` to retrieve all the items and also use a counter to show a progress bar!

**Comment by blueelvis** [comment]
@thgreasi - Thanks a lot for the suggestions! I will use this in the solution :)
