### ISSUE TITLE
Advice Please on upgrade to 1.5

### ISSUE THREAD

**Issue by SteveBrooker** [localForage/localForage#731]
I have been using localForage v1.3 for over two years with no issues for an app that is available on IOS, Android, Chrome Web Store, MacOS and Windows 10.

I am about to upgrade to localForage v1.5 and I note that the primary new feature is that on Safari 10+/Mobile Safari 10.1+ the default is to now used IndexedDB rather than WebSQL, and I understand defaults the opposite way for older versions of Safari. 

I believe that for localForage v1.3, the default was to use IndexedDB if it existed, which is did on mobileSafari since IOS 8 even if it was unreliable. My app users therefore were using IndexedDB even it was unreliable, hence upgrading to v1.5 presents no problem, just the removal of the unreliability.

However what I would like some advice on now, is what I will need to do to support those of my existing user base who are still on IOS 8,9 and 10.0, when they get an app upgrade from me containing localForage v1.5? Presumably it will (from what I have read) no longer default to IndexedDB and rather it will default to WebSQL and they will no longer see their stored data.

**Comment by thgreasi** [comment]
With #723 (which is targeted for v1.5.1) we are planning to allow overriding the `_support` method of the internal drivers. [Here](https://github.com/localForage/localForage-compatibility-1-4/blob/master/lib/index.ts) is the code of a WIP plugin that will offer compatibility with LF1.4 Safari IndexDB detection.

**Comment by thgreasi** [comment]
> I believe that for localForage v1.3, the default was to use IndexedDB if it existed, which is did on mobileSafari since IOS 8 even if it was unreliable.

Actually, [lf 1.3 does include a safari check](https://github.com/localForage/localForage/blob/1.3.3/src/localforage.js#L50-L83). And that's also true from [lf 1.3.0](https://github.com/localForage/localForage/blob/1.3.0/src/localforage.js#L57-L84).
So I guess you should follow the same process as from upgrading from lf 1.4 .

**Comment by thgreasi** [comment]
In other words, you will be able to use the [localForage-compatibility-1-4 plugin](https://github.com/localForage/localForage-compatibility-1-4) when it is released to upgrade to v1.5.1.

**Comment by thgreasi** [comment]
@SteveBrooker [localForage-compatibility-1-4](https://github.com/localForage/localForage-compatibility-1-4) was just released to resolve the safari migration issue. Please check it out, I hope that you will like it.
Closing this for now. Feel free to re-open in any case.
