### ISSUE TITLE
I can't use the extension localforage-getItems() 

### ISSUE THREAD

**Issue by dougbatista** [localForage/localForage#736]
My package.json:

"localforage": "^1.5.0",
"localforage-getitems": "^1.3.0"

//My import:
import localforage from "localforage";

//My usage:
showItems(){
       //the method getItems is not avalible to me 
      localforage.getItems().then(function(results) {
      console.log(results);
});

I'm using on an Ionic 2 project. This lib is not accepted in TypeScript ?

**Comment by thgreasi** [comment]
Just released localforage-getitems v1.4 with typings.
You should use the `extendPrototype()` method.
Take a look at the [typing tests](https://github.com/localForage/localForage-getItems/blob/master/typing-tests/index.ts) on how it is used.
