### ISSUE TITLE
Security vulnerability reported by 'retire'

### ISSUE THREAD

**Issue by rahul-desai3** [localForage/localForage#737]
I have been testing out my project for security vulnerabilities using the NPM module "retire" (https://www.npmjs.com/package/retire). `NeDB` is one of the NPM modules that I use which has `local-forage` as its dependency. Below is the security vulnerability reported by retire:

```
node_modules/nedb/node_modules/localforage/docs/scripts/jquery.min.js
↳ jquery 1.9.1 has known vulnerabilities: severity: medium; issue: 2432, summary: 3rd party CORS request may execute; jquery/jquery#2432 http://blog.jquery.com/2016/01/08/jquery-2-2-and-1-12-released/
```

I have also reported this in the NeDB issues here: https://github.com/louischatriot/nedb/issues/526

**Comment by tofumatt** [comment]
This is not an issue with the actual library but just a jQuery issue with the docs page. Which is a static page.

We can upgrade jQuery on that page but this is not an actual security vulnerability.
