### ISSUE TITLE
Add encryption

### ISSUE THREAD

**Issue by piupiupiu** [localForage/localForage#74]
Hello.

Do you have any plans to add the encryption support? It's not quite safe to store some sensitive data as is. I think it is better to have a built-in encryption support rather that adding 3-d party bicycle.

**Comment by Bertg** [comment]
Hi all, Sorry for waking up this thread. 

I was looking into implementing a solution to encrypt data for localForage in a transparent way.
Initially i though that doing this using a custom Driver would be the best way to go; but then a lot of the serialisation logic provided by localForage would be lost.

This lead me to look for a way to replace the serialiser. I would implement a new serialiser that wraps the existing serialiser. 

@tofumatt Do you think this would be an acceptable change to the localForage API ?

**Comment by tofumatt** [comment]
Hi @Bertg,

The serializers are available in their own modules I believe so you should be able to re-use them. I think each driver chooses its serialiser so you might want to check the existing drivers to see how they work and what you would want to do in a custom driver that adds encryption.

That said, if further modularisation is required and is straightforward I'm all for it. I think that's separate to this issue so if you want to improve the modularity of serialisers please open a new issue to track it. I'm not sure it's needed for custom drivers but if it was and had tests I'm cool with it.
