### ISSUE TITLE
Problems with older Android systems? (5.1.1)

### ISSUE THREAD

**Issue by ssuess** [localForage/localForage#752]
Hi I have been testing an app where I am using (1.5.2) localforage, and on older Android versions (such as my test emulator 5.1.1 on Nexus 4 API 22), I am noticing some strange behavior where keys just disappear from the localforage db. Are there known problems  like this on older systems? The strange thing is, some of the keys remain in the db, and only some of them disappear, and I can't seem to find any pattern to which. On newer versions of Android and ios, everything works exactly as expected, and the keys never disappear.

**Comment by thgreasi** [comment]
Hey @ssuess , here are my questions to help track this down:
Did this occurred after an upgrade to LF 1.5.2 and didn't happen before?
Are you using custom drivers?
Setting custom driver order?
Setting custom store sizes?
Using `createInstance()`?

**Comment by thgreasi** [comment]
Also what can you check the result of `localforage.driver()` both on load of the app and after using the store for some time.

**Comment by ssuess** [comment]
Hi, thanks for the reply. To answer your questions:
1. No, this happens regardless of version, although I did also update to 1.5.2 to see if that fixed it.
2. Not using custom driver
3. Not setting driver order
4. Not setting store sizes
5. Not using `createInstance()`
6. The results of `localforage.driver` on both working and non working systems is `asyncstroage`

Here are the really odd things to me:
1. SOME (but not all) items get stored and then disappear, and it is always the same keys that disappear, the ones I am using in an `axios` call that contain values for username and bearer token
2. I would expect this to be a problem somewhere in my code, except that this only happens on Android 5.x and below. All later versions are fine, Mac and Windows and iOS are all fine and working as expected. They keep the stored values I have set, all of them.

**Comment by tofumatt** [comment]
Hmm, yeah, it sounds like it could be a bug in the underlying IndexedDB system; if it’s always using asyncStorage but certain data isn’t getting stored.

What is the exact data structure of the value you’re storing in the “axios” key? It could be something IndexedDB can’t handle? Maybe there’s a circular object or something?

**Comment by ssuess** [comment]
no, one is just a username string, and the other is a JWT token, also a string. And the really bizarre thing is that they had to exist for a short time, because the other data that remains in localforage (arrays and strings btw) could not have been retrieved via the axios call unless the token was present. it is just that the token and username keys completely disappear before making the next call to the REST API. It is like there is a timer set on them to self destruct/erase after a few seconds.

**Comment by ssuess** [comment]
Ok, I am still not entirely sure what is causing this, but I think now the bug is  two part, one related to Android 5 redirecting me, and one related to localforage.clear() not fully executing.

1. For some reason, the code in Android 5 and below was forcing a return to the login page immediately after login. 
2. on logout (and also on load of login page), I had a localforage.clear() command run, BUT because it was not actually clearing everything from localforage, I was confused.
3. If I remove my localforage.clear() commands, all my keys are still present. (even though I am still mysteriously being returned to the login page in Android 5 and below)

so I think perhaps there is a bug in localforage.clear (not clearing all keys sometimes), but to be clear (pun intended) if I call if directly, even in Android 5, it WILL clear all keys. Just not when Android is redirecting me back to login...

**Comment by ssuess** [comment]
Ok, I have finally solved this, at least to my satisfaction. What was happening is that I was testing for the presence of my token on my dashboard page (that was forwarded from the login page) and it was not yet set (promise had not completed, race condition), so I put moved my forward to the callback (then) of my setItem for the token. I can only guess as to why older devices were the only ones with this problem, perhaps the code/emulated hardware is faster on newer ones, so the promise always completed before the page forward, and that is why I never saw it on anything newer. Anyway, thanks for helping me troubleshoot this.

**Comment by thgreasi** [comment]
:+1: and thanks for sharing all those details:+1:
