### ISSUE TITLE
Will operation ordering be preserved? [General Design Question]

### ISSUE THREAD

**Issue by stkao05** [localForage/localForage#754]
Hi guys,

This is more of a general open question regarding the design of localForage. Here is the example scenario:

```
localforage.setItem('foo', '1');
localforage.setItem('foo', '2');
```

Suppose both `setItem()` calls finished successfully. Will "foo" guarantee to have a value of "2", or there is a possibility that "foo" could be "1"?
___

Looking at the source codes, I am suspecting the answer is no due to the fact that the persistence calls are carried out inside of Promise chain. 

Just would like to know what are you guys thought on this? Do you guys think this property should be supported? 

(This is just my speculation so please correct me if I am wrong)

**Comment by tofumatt** [comment]
There is no guarantee in that example that "foo" would have a value of "2". As you mentioned, localForage stores data asynchronously by design so you would need to wait for the Promise to complete to know the data was stored.

If you wanted a clearer syntax you could use ES7's async/await:

```js
await localforage.setItem('foo', '1');
await localforage.setItem('foo', '2');
const value = await localforage.getItem('foo');
```

`value` would be `'2'` in that case.

**Comment by thgreasi** [comment]
So, this goes down to the guaranties that the underlying storage methods provide.
I would for sure detect race conditions and have them not run in parallel, or even avoid storing `1`.
On the other hand [here is a codepen example](https://codepen.io/thgreasi/pen/BwGraG) which gave pretty consistent results. I guess the fact that JS is single threaded (except from workers) has something to do with it, but still I wouldn't be 100% sure and wouldn't base business critical stuff on this observation.

**Comment by stkao05** [comment]
Hi @thgreasi @tofumatt 

Thank you for the explanation :) I would like to raise a couple of questions if you guys don't mind. 

__Expectation of Async Storage__

I think asynchronous storage could still support "operation ordering" property. As matter of fact, I think these two concepts don't really contradict. 

IndexedDB is an asynchronous storage but it still supports such an "operation ordering" property: it ensures the result of the operation will be in the same ordering which transactions are created. 

```
// example from MDN
var trans1 = db.transaction("foo", "readwrite");
var trans2 = db.transaction("foo", "readwrite");
var objectStore2 = trans2.objectStore("foo")
var objectStore1 = trans1.objectStore("foo")
objectStore2.put("2", "key");
objectStore1.put("1", "key");

// After the code is executed the object store should contain the value "2", since trans2 should run after trans1.
```


__Why supporting such a property is essential__

If localforage does not provide such a guarantee, it will be left as client's responsibility to implement some async control to ensure correctness of preserved value.

This could be an issue because I believe this is the scenario where most clients will encounter, which means most clients will need to implement this logic to ensure application correctness.

**Comment by tofumatt** [comment]
Yes, the client/developer needs to use the async api. Implementing what you’re talking about seems really intense for no benefit as async code is very normal in JS and I don’t see how a synchronous api for something that is underneath async is useful.

While I suppose you could implement something like this I don’t think localForage should. The asynchronous model has served us well and the new ES7 syntax makes it even nicer :-)

- Matt (Sent from mobile)

**Comment by thgreasi** [comment]
I think that if IndexedDB provides sick guarantees, then we probably can assume that the same is true for the three IndexedDB driver of localforage, which is demonstrated by my earlier example.
