### ISSUE TITLE
Support multiple criteria query, paging, sorting

### ISSUE THREAD

**Issue by xiaojun515688** [localForage/localForage#758]
similar mysql select * from table where col1 in ('1001','1002') order by create_time desc limit 0,10

**Comment by tofumatt** [comment]
It looks like you're asking for a SQL API for localForage–unfortunately this is out of scope for the aim of the project. While there are some extensions (https://github.com/localForage) this kind of API is not the aim of localForage as a key/value store with a simple API.

You might want to try using IndexedDB directly or a project like PouchDB if you want a more powerful query API 😄
