### ISSUE TITLE
1.5.4 typings broke signature

### ISSUE THREAD

**Issue by michaelgeorgeattard** [localForage/localForage#762]
Hi,

In 1.5.4 `defineDriver` started expecting `dropInstance` method in driver configuration object. Preferably signature changes are released as major versions (2.0.0 ?). Or maybe `dropInstance` could be made optional.

Consider also adding `dropInstance` documentation to this section:
https://github.com/localForage/localForage/blob/master/docs/api.md#driver-api

Thanks

**Comment by tofumatt** [comment]
Yup, this was my bad. I forgot about the `dropInstance` change when I merged a fix for #760 and released `1.5.4`. I will be releasing `1.5.5` later today which will remove the API change and `1.6` will include the new API. Sorry about that!

**Comment by michaelgeorgeattard** [comment]
Thanks @tofumatt. I was wondering if `2.0.0` would be a better release version because of how `defineDriver` is set up to expect the configuration object; and any addition to this configuration is a breaking change.

**Comment by thgreasi** [comment]
@michaelgeorgeattard I will change that to make `dropInstance` as it should be. Sorry for the inconvenience.

**Comment by tofumatt** [comment]
FYI I've published `1.5.5`, which includes Edge support for IndexedDB but removes the extras added in this patch. Sorry about that!

**Comment by chetmurphy** [comment]
What about exporting the typescript interfaces (especially LocalForage)? With 1.5.5 I see no way to store the value returned from createInstance and still have type checking in typescript.

**Comment by chetmurphy** [comment]
What does dropInstance do? I did not even find a reference to it in the code.

**Comment by alan-agius4** [comment]
Check the docs here:
https://github.com/localForage/localForage/blob/master/docs/api.md

**Comment by chetmurphy** [comment]
Thanks, that works.

--Chet

________________________________
