### ISSUE TITLE
Allow non-performance based support check for IndexedDB on Safari

### ISSUE THREAD

**Issue by twolfson** [localForage/localForage#763]
We are currently using `localForage` as a simplified IndexedDB interface to save large native objects (e.g. 1MB large typed arrays) as part of an autosave functionality

It's been working great but we recently learned that older mobile Safari supports IndexedDB but is failing our support check due to performance concerns listed in:

- https://github.com/localForage/localForage/pull/651
- https://github.com/localForage/localForage/issues/650
    - Side note: PouchDB PR referenced here was never actually landed =/
    - https://github.com/pouchdb/pouchdb/pull/6173
- https://github.com/localForage/localForage/issues/604

Due to the size of our typed arrays and the frequency of them being saved, we think it's impractical to use other storage methods. For the interim, we've forked and removed the Safari checks (relying exclusively on `IndexedDB` existing):

https://github.com/StandardCyborg/localForage/commit/08eb4bda2fd923ca5c16d7acb6be1791c89455b5

However, for a long term solution, we were wondering if it would be possible to allow users to force using a specific driver when it's supported at its core and they understand the performance concerns

**Comment by twolfson** [comment]
I should also mention that iOS 10 mobile Chrome seems to also lack `fetch` support whereas iOS 11 mobile Chrome seems to have it

**Comment by thgreasi** [comment]
So, I'm not sure I get your request correctly, but would it make sense to run any custom detection code before as part of your app and then just call `setDriver()` with the one that makes more sense to your use case?
Also, as of localforage 1.5.1 you can actually override the _support check. Please take a look at what we do in [localForage-compatibility-1-4](https://github.com/localForage/localForage-compatibility-1-4).

**Comment by twolfson** [comment]
We probably could copy/paste/modify the `isIndexedDBValid` code as we've done in the fork. The issue is pedantically we the validation code should only state whether or not the driver can be used; not whether or not it will be more performant than others (which is the reason for the Safari/`fetch`) lines

From what I can tell, this code was mostly introduced so there's an automatic fallback chain for supported drivers to optimize performance. I was wondering if that code could be relocated elsewhere (e.g. `_shouldUse` in addition to `_supports`) where `_getSupportedDrivers()` can first reject any non `_shouldUse` but then fallback to `_supports` if there were no drivers found

**Comment by tofumatt** [comment]
I thought there was an actual issue with multiple stores or databases simultaneously being accessed in Safari as well, but if it’s just performance that’s an interesting point.

- Matt (Sent from mobile)

**Comment by thgreasi** [comment]
Yea, there was an actual issue with safari  <10.2 and that's why we avoided it. In short, you couldn't have an orange store and a car store and have each each one hold a record with the same ID. People make test cases for that that only failed on safari! Google it, it's a nice read.

**Comment by thgreasi** [comment]
The single preference order mechanism is the DefaultDriverOrder array in src/localforage.js

**Comment by twolfson** [comment]
Ah, okay. Will close then due to actually buggy code for the general use case 👍 Thanks y'all
