### ISSUE TITLE
Is there an API to query how many instance existed and iterate them?

### ISSUE THREAD

**Issue by afayp** [localForage/localForage#765]
such as I've created many Instance. how can I iterate them and get their names? i can't find any related api in documents.Please help me. thanks!

**Comment by thgreasi** [comment]
No, unfortunately not.
You should have a "master" instance to store such information and maintain those info on your app's side.
Maybe on v2 we could do something like this inside LF.
Duplicate of #719

**Comment by afayp** [comment]
OK! Thanks for your response!
