### ISSUE TITLE
How to build localForage without WebSQL or localStorage ? 

### ISSUE THREAD

**Issue by finscn** [localForage/localForage#771]
The target platform of my web app supports IndexedDB , I want to use it only .
So I want to build a version without WebSQL or localStorage  for minimizing the size of localForage.

How to do it ?

Thanks.

**Comment by tofumatt** [comment]
This is not explicitly supported by localForage (right now), but you could have a look at our `npm run build` script and create a version that does not include the other drivers (by removing their import calls). There is unfortunately little documentation on this right now.

**Comment by finscn** [comment]
Where can I find `npm run build` script ?

**Comment by tofumatt** [comment]
That’s in the package.json file at the root of the project. You’ll need to understand grunt/webpack/Babel to get things to work. Sorry, it’s a bit complicated :-/

**Comment by finscn** [comment]
I don't have any knowledge about grunt/webpack/Babel  ... So sad...
But I know learning is my duty .

Thanks.
