### ISSUE TITLE
1 million objects JSON

### ISSUE THREAD

**Issue by strix25** [localForage/localForage#772]
Can this hold up to 1 million objects in JSON ?

**Comment by thgreasi** [comment]
That obviously depends on how big are your objects and the limits of the browser it is going to run.
That would be easy to test, just using a for loop should be enough along with some representative properties and values.

**Comment by strix25** [comment]
If I put it in local json file it is 126MB :\

**Comment by tofumatt** [comment]
Just so you know part of the original use case for localForage was storing large (50mb+) MP3 audio files for podcasts. 126mb should be fine. If it’s in one big object it might be a bit of a memory issue but there’s no problem storing that amount of data.
