### ISSUE TITLE
dropInstance test occasionally timeout

### ISSUE THREAD

**Issue by salomvary** [localForage/localForage#779]
On a fresh clone created like this:

```
git clone https://github.com/localForage/localForage.git
cd localForage
npm install
bower install
```

Tests hang at this line:
```
npm test
[...]
Running "mocha:unit" (mocha) task
Testing: http://localhost:9999/test/test.main.html
```

Same thing happens with `grunt test`.

Versions:
Node: v8.6.0
Npm: 5.6.0
Bower: 1.8.2
macOS: 10.12.6 (16G1114)

**Comment by tofumatt** [comment]
Thanks for filing!

I've noticed testing has problems too. I think we really have to spend some time updating the test suite. Maybe I can resurrect my karma branch soon. 🤔

**Comment by salomvary** [comment]
It might be related that "asyncStorage driver dropInstance / drops an other instance without affecting the rest" sometimes times out on Firefox and almost always in iOS Safari when using `/test/test.main.html` directly from the browser. Even if it does not time out, tends to be very slow.

![screen shot 2018-01-09 at 14 56 12](https://user-images.githubusercontent.com/193923/34724319-ae94d150-f54d-11e7-8fd1-162577f477c2.png)

**Comment by thgreasi** [comment]
@salomvary I've noticed that and I'm working on it for some weekends now.

**Comment by thgreasi** [comment]
So, made some progress during this weekend, after putting some effort on trying to close all idb connections and store proper db references (no PR yet though). 
Status:
* The first call to dropInstance to drop a store might take some seconds until all connections are closed.
* Dropping a non-existing db rejects in IDB driver, which is currently a thing that I want to change for consistency. Should not be that hard.
* All other dropInstance calls are now consistently resolving in a timely manner.
