### ISSUE TITLE
No localforage.dropInstance

### ISSUE THREAD

**Issue by salomvary** [localForage/localForage#785]
Despite what [the documentation](https://localforage.github.io/localForage/#multiple-instances-dropinstance) suggests there is no `localforage.dropInstance()` exposed. (Neither on the global `localforage` nor on instances returned from `createInstance`).

Using localforage 1.5.5 Chrome 63.0.3239.132.

I saw some commits related to `dropInstance` on `master` but could not figure out what happened, 1.5.5 seems to have been released from somewhere else than `master`.

**Comment by thgreasi** [comment]
Actually this is a new method that got merged but I want to make some improvements before cutting a release. Will try to do asap. Thanks for the reminder.
Last update in #779

**Comment by salomvary** [comment]
I see. Then this is a documentation issue, I expected the API docs to reflect the latest release while it is actually in sync with the latest commit on master.

**Comment by tofumatt** [comment]
Yeah, that's a good point. Right now the docs are updated automatically so commits to master update them. Maybe in the future we could update the docs site only on a tag, like we do with our automated `npm publish`.

**Comment by salomvary** [comment]
Or maybe just leave a warning about this fact on the documentation pages.  One can still [access API docs for a specific version](https://github.com/localForage/localForage/blob/1.5.5/docs/api.md) by going to the given release/tag..

**Comment by thgreasi** [comment]
Just released v1.6.0 :)
