### ISSUE TITLE
cdnjs.com version 1.5.7 broken (404 Not Found)

### ISSUE THREAD

**Issue by CTassisF** [localForage/localForage#795]
Looks like all the files of localforage v1.5.7 hosted on cdnjs.com are broken (404 Not Found):

https://cdnjs.cloudflare.com/ajax/libs/localforage/1.5.7/localforage.js
https://cdnjs.cloudflare.com/ajax/libs/localforage/1.5.7/localforage.min.js
https://cdnjs.cloudflare.com/ajax/libs/localforage/1.5.7/localforage.nopromises.js
https://cdnjs.cloudflare.com/ajax/libs/localforage/1.5.7/localforage.nopromises.min.js

Can you please fix them?

Thanks in advance.

**Comment by tofumatt** [comment]
Thanks for filing the bug, I’ll look into this ASAP, sometime this morning.

**Comment by thgreasi** [comment]
Interestingly enough, it shows up properly in unpkg: https://unpkg.com/localforage@1.5.7/dist/localforage.js

**Comment by tofumatt** [comment]
I don't think we did anything that would've stopped this from being published... could it be a CDNJS bug?

**Comment by thgreasi** [comment]
More interestingly enough, [our dist files can be found](https://github.com/cdnjs/cdnjs/tree/master/ajax/libs/localforage/1.5.7) in their repo!?

**Comment by CTassisF** [comment]
It seems to be working now.

**Comment by tofumatt** [comment]
Sweet, I guess it was just a temporary issue with their site then. I'll close this.

Thanks for letting us know.
