### ISSUE TITLE
API docs translation site in Chinese

### ISSUE THREAD

**Issue by xmoyKing** [localForage/localForage#796]
hi, I've translated the doc page into Chinese as blow:

[localForage in Chinese](https://localforage.docschina.org)

so, I'd like to add the link of Chinese site on the official page, could I?

**Comment by tofumatt** [comment]
This is really cool! I think for now we could link to your site but in the future it might be good to set up a real translation system.

Thanks!

- Matt (Sent from mobile)

**Comment by xmoyKing** [comment]
That will be really good for all developers and users. 

Expecting the new system!
