### ISSUE TITLE
Documentation | Loading localforage

### ISSUE THREAD

**Issue by abelardolg** [localForage/localForage#803]
Hi, 

These lines:
<script src="localforage.js"></script>
<script>console.log('localforage is: ', localforage);</script>
don't load localforage.

When I use in Angular, I need mention (inside the index.html file) its path under the node_modules dir, such as:

> <script src="../node_modules/localforage/dist/localforage.js"></script>
> <script>console.log('localforage is: ', localforage);</script>

but once loaded the browser displays a message:
![image](https://user-images.githubusercontent.com/22522883/38021699-e404a10e-327d-11e8-884e-02f93b6db199.png)

I think is a bug, maybe?

Brs.

**Comment by tofumatt** [comment]
It looks like the network request to load localForage was aborted, so it never loaded the file. What does you network request panel show? I’m guessing the path to localforage.js is a 404.

**Comment by abelardolg** [comment]
![image](https://user-images.githubusercontent.com/22522883/38022938-35a2cbe6-3281-11e8-8dff-b7f8b6c55589.png)

![image](https://user-images.githubusercontent.com/22522883/38022947-405f39d4-3281-11e8-8199-d0e9dfd3281c.png)

**Comment by abelardolg** [comment]
According to the documentation...

![image](https://user-images.githubusercontent.com/22522883/38023030-73828488-3281-11e8-8c47-bb395e11ba28.png)

```
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>SGE 2018 - Lavadero BackOffice</title>
  <base href="/">

  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="icon" type="image/x-icon" href="favicon.ico">
  <script src="localforage.js"></script>
  <script>console.log('localforage is: ', localforage);</script>

  <link rel="stylesheet" href="https://unpkg.com/ngx-bootstrap/datepicker/bs-datepicker.css">
  <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
</head>
<body>
<div class="container col-10">
  <app-root></app-root>
</div>
</body>
</html>
```

**Comment by tofumatt** [comment]
The network panel there shows the request for `localforage.js` is not found (404).

Your path: `http://localhost:4204/node_modules/localforage/dist/localforage.js` doesn't seem to be being served by your web server.

You might want to check out something like webpack server for development if you run into more path issues.

Since this isn't an issue with localForage I'm closing it, thanks for the extra info about the network request.

**Comment by abelardolg** [comment]
But in your documentation you wrote we should include the "localforage.js" inside the index.html.
If you read my last comment, I did this but this .js didn't load.
