### ISSUE TITLE
Offline mode cannot load localForage

### ISSUE THREAD

**Issue by lvendramini** [localForage/localForage#804]
I ran through the tutorial 
https://codelabs.developers.google.com/codelabs/your-first-pwapp/index.html?index=..%2F..%2Findex#4

And replaced the localDB with localForage.  All worked great, unless I turned the service worker to offline mode.  When offline, localForage is "not known".  

I initialized it in the index.html in the header

  <script src="scripts/localforage.js"></script>
    <script>localforage.config({
            driver: localforage.WEBSQL, // Force WebSQL; same as using setDriver()
            name: 'myFirstPWAPP',
            version: 1.0,
            size: 4980736, // Size of database, in bytes. WebSQL-only for now.
            storeName: 'My_1_st_pwapp_app', 
            description: 'Will store local data for my first pwapp app'
        });</script>

and within the app.js 

I call localforage.put(.....) and localforage.get(....). 
It errors within app.js --> " localforage is not defined"
I am using chrome v 65.0

**Comment by lvendramini** [comment]
Request URL: http://127.0.0.1:8887/scripts/localforage.js
Referrer Policy: no-referrer-when-downgrade
Provisional headers are shown
Referer: http://127.0.0.1:8887/
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36

Nothing in the response

**Comment by lvendramini** [comment]
The FetchEvent for "http://127.0.0.1:8887/scripts/localforage.js" resulted in a network error response: the promise was rejected.
Promise.catch (async)
(anonymous) @ service-worker.js:73
service

**Comment by lvendramini** [comment]
Fixed it...in my service worker I didn't include localforage.js.  Thanks!

**Comment by tofumatt** [comment]
No worries, happy it was fixed! 😄
