### ISSUE TITLE
Issue with Safari mobile 10.0

### ISSUE THREAD

**Issue by karneaud** [localForage/localForage#809]
I'm using the 1.7.1 version and still encounter the same issue....is it that I should try the `localforage-compatability"

**Comment by tofumatt** [comment]
What is the issue you're encountering? You posted in the other repo as well but did not state your issue. `localforage-compatability` is for users who are upgrading from localForage 1.4 to 1.5.

**Comment by tofumatt** [comment]
Looking at your other issue, I think you should check with https://github.com/championswimmer/vuex-persist, as I don't see a localForage-specific issue here. I don't know anything about that library but it does say it has localForage support.

If you have an issue with localForage please do post it on this repo 😄
