### ISSUE TITLE
Angular FESM modules have imports that produce 'undefined value' exceptions

### ISSUE THREAD

**Issue by maxtacco** [localForage/localForage#814]
Hi,
I'm using localforage 1.7.1 in one of the library modules created using Angular CLI 6.0.0-rc.6 (@angular-devkit 0.5.8). My code in one of the services looks like this:
```javascript
import * as localforage from 'localforage';

@Injectable()
export class LocalStorageService {
  public setItem<T>(key: string, value: T): Observable<T> {
    return Observable.fromPromise(localforage.setItem(key, value));
  }
}
```
Angular CLI internally uses ng-packagr/rollup to create bundles for a number of module types. 

For FESM5 and FESM2015 generated bundles look something like this:
```javascript
import { setItem, getItem, removeItem } from 'localforage';
...
LocalStorageService.prototype.setItem = function (key, value) {
  return Observable.fromPromise(setItem(key, value));
};
...
```
Unfortunately, this produces 
```
Uncaught TypeError: Cannot read property 'ready' of undefined
    at localforage.js:916
```
As you can see the methods got imported in this case and 'self' references in localforage code are undefined as a result.

So, is there a way to import localforage in order for it to work in FESM bundles?

The only solution I came up with so far was to replace "import * as localforage from 'localforage'" with: 
```
const localforage = require('localforage');
``` 
to prevent rollup in this case.

**Comment by thgreasi** [comment]
That does seem like an extreme code optimization from rollup. I think that you should open an issue at rollup to get their opinion on this. It seems that `import localforage = require('localforage');` is the way to go for your case, which is kind of expected since localforage is a UMD package.
