### ISSUE TITLE
Storage Quota Calculation Change in Chrome 66

### ISSUE THREAD

**Issue by CrimsonTideDevelopment** [localForage/localForage#815]
I am aware that this not an issue with localforage, this is more of a PSA as I cannot find this change publicly documented anywhere other than a couple of chromium commits and issues raised internally to chromium.

As per chromium commit https://chromium.googlesource.com/chromium/src.git/+/1e5b5704d062321a0c6d000224573661029b4b19
calculation of minimum reserved disk space has been altered from 1% to a flat 1GB.

Other than the drastic change in limit for any device with <100GB disk space, and the lack of warning (as I said as far as I can tell), I can see that this causes some headaches in a couple of seemingly fairly common scenarios (I say this as our customers are having sufficient issues that we are now re-writing not only our storage system but also our background sync engine which operates inside of a Web Worker using IndexedDB).

A device with very low disk space as standard (e.g. Samsung J3 2016 with 8GB) will have around 4GB free space after default apps and Android are installed, it does not require much to be installed or done on the device before it dips below 1GB - through entirely routine usage. At this point the device stops being able to write to IndexedDB through LocalForage as the Storage quota is automatically exceeded.

In our case, the update to M66 has caused our hybrid app to cease working on a significant subset of our customer's devices, overnight, as a number are using cheaper devices which were already hovering around 800-950mb used. This is despite our app only using about 5-35mb of IndexedDB storage.

If anybody has any ideas around where to move this onto next, if at all, then I'm happy to help and am all ears!

**Comment by CrimsonTideDevelopment** [comment]
To give an update on this - we raised a bug with Chromium who, wonderfully, have revised this change and are estimating it will be rolled out in M67 - link to the bug here: https://bugs.chromium.org/p/chromium/issues/detail?id=838816

**Comment by tofumatt** [comment]
Thank you so much for that! Sorry for not responding but I did see this issue and meant to deal with it this weekend. I started a new job recently so have been a bit busy! 😄

Thank you a lot for flagging this with the Chromium team 👍
