### ISSUE TITLE
Uncaught (in promise) DOMException in setItem

### ISSUE THREAD

**Issue by gonzaloserrano** [localForage/localForage#816]
Hi,

I'm using localForage for a mobile project using cordova. I have checked with the latest version (1.7.1) that with the device disk full the library fails with this error:

```
Uncaught (in promise) DOMException
transaction.onabort.transaction.onerror @ localforage.js:1057
```

![screenshot 2018-05-09 18 57 28](https://user-images.githubusercontent.com/349328/39828454-5696bbea-53bb-11e8-843a-c3fb5542a1d4.png)

I think it could be similar to https://github.com/localForage/localForage/issues/800.

Thanks.

**Comment by midhunadarvin** [comment]
I am also getting this issue on some mobile devices only. Most of them are older devices.

**Comment by gonzaloserrano** [comment]
I noticed that the exception wasn't catched because I had a `setItem()` call without `await`. So I ended up doing `setItem(...).catch((error) => { // handling error.code 22 })`.

**Comment by tofumatt** [comment]
Awesome, thanks for letting us know! 👍
