### ISSUE TITLE
Various problems with localForage + cordova + ionic

### ISSUE THREAD

**Issue by Hanzofm** [localForage/localForage#817]
Hi,

I am having various problems with the use of this library.

**First:**

With the newest version of library (1.7.1) when I try to build with --prod flag the compilations returns this error:

```
Running 'serve:before' npm script before serve
> myapp@ watch /Users/dev/DEV/MOBILE/myapp
> ionic-app-scripts watch --copy copy.config.js
[21:23:32]  ionic-app-scripts 1.1.4
[21:23:32]  watch started ...
[21:23:32]  build dev started ...
[21:23:32]  clean started ...
[21:23:32]  clean finished in 1 ms
[21:23:32]  copy started ...
[21:23:32]  transpile started ...
[21:23:37]  typescript: node_modules/@types/localforage/index.d.ts, line: 7
Subsequent variable declarations must have the same type. Variable 'driver' must be of type 'string |
[21:23:37]  typescript: node_modules/@types/localforage/index.d.ts, line: 15
[21:23:37]  typescript: node_modules/@types/localforage/index.d.ts, line: 25
[21:23:37]  typescript: node_modules/@types/localforage/index.d.ts, line: 25
[21:23:37]  typescript: node_modules/@types/localforage/index.d.ts, line: 100
[21:23:37]  typescript: node_modules/localforage/typings/localforage.d.ts, line: 47
[21:23:37]  typescript: node_modules/localforage/typings/localforage.d.ts, line: 52
[21:23:37]  typescript: node_modules/localforage/typings/localforage.d.ts, line: 113
[21:23:37]  transpile failed
string[]', but here has type 'string | LocalForageDriver | LocalForageDriver[]'.

L6:      size?: number;
L8:      storeName?: string;

Subsequent variable declarations must have the same type. Variable 'version' must be of type 'number', but
here has type 'string'.

L15:  interface LocalForageDriver {
L16:      _driver: string;

Subsequent variable declarations must have the same type. Variable '_support' must be of type 'boolean |
LocalForageDriverSupportFunc', but here has type 'boolean | Promise<boolean>'.

L24:      getItem(key: string, callback: (err: any, value: any) => void): void;
L26:      key(keyIndex: number, callback: (err: any, key: string) => void): void;

All declarations of '_support' must have identical modifiers.

L24:      getItem(key: string, callback: (err: any, value: any) => void): void;
L26:      key(keyIndex: number, callback: (err: any, key: string) => void): void;

Duplicate identifier 'export='.


Interface 'LocalForageDriver' incorrectly extends interface 'LocalForageDbMethods'. Types of property
'getItem' are incompatible. Type '(key: string, callback: (err: any, value: any) => void) => void' is not
assignable to type '{ <T>(key: string): Promise<T>; <T>(key: string, callback: (err: any, value: T) =>
void): void; }'.

L46:  interface LocalForageDriver extends LocalForageDbMethods {
L47:      _driver: string;

All declarations of '_support' must have identical modifiers.

L51:      _support?: boolean | LocalForageDriverSupportFunc;

Duplicate identifier 'export='.

L112:      export = localforage;

[21:23:37]  watch ready in 4.71 s
Running live reload server: http://localhost:35729
Watching: www/**/*, !www/lib/**/*, !www/**/*.map
√ Running dev server:  http://localhost:8100
Ionic server commands, enter:
restart or r to restart the client app from the root
goto or g and a url to have the app navigate to the given url
consolelogs or c to enable/disable console log output
serverlogs or s to enable/disable server log output
quit or q to shutdown the server and exit

ionic $ [21:23:37]  copy finished in 4.75 s
```

If I go to the folder (node_modules/@types/ and remove the folder 'localforage' the build works fine.
This problem not occurs with version 1.4.0 of the library.

**Second:**

When I do multiple writes, with setItem on some devices the second write crashes returning an error:
For example:

this.localStorageProvider.setAccesstoken('token');
this.localStorageProvider.setSomeFlag('flag');

second write returns:

`{"__zone_symbol_currentTask":{"type":"microTask","state":"notScheduled","source":"Promise.then","zone":"angular","cancelFn":null,"runCount":0}}`

What would be the problem?

**Comment by thgreasi** [comment]
I'm not sure how to debug the second issue with that limited context. We actually have test cases for concurrent setItem calls, so there should be something else involved. Please also confirm the driver preference order used.

Regarding the first issue, ionic has LF v1.4 and the respective `@types` as a dependency of ionicStorage. Since LF v1.5 we provide the typings as part of the npm module itself, since it was talking too much time to get it shipped when using `@types`. As a result if you are using LF instead of ionicStorage, then you should remove ionicStorage from your dependencies because it's typing dependency conflicts with newer versions of LF.

**Comment by Hanzofm** [comment]
Hi, regarding to first issue, it is solved, thanks.

On second issue my 'architecture' is:

A provider to manage localForage stuff  (wich is defined as a provider in app.module.ts) like this:

```
import localForage from 'localforage';
@Injectable()
export class LocalStorageService {

  constructor() {
  }

  setSomeData(data: string) {
    return localForage.setItem('someData', data);
  }

  setSomeData2(data: string) {
    return localForage.setItem('someData2', data);
  }

getSomeData() {
    return localForage.getItem('someData');
  }

  getSomeData2() {
    return localForage.getItem('someData2');
  }

  printDriver() {
    console.log(localForage.driver())
  }
```


I don't configure nothing related to the driver in my app and if I print the driver when device is ready with:

`this.localStorageService.printDriver()`


It prints:

`asyncStorage`

Thanks for your help

**Comment by thgreasi** [comment]
Does it print the same even after the first call to setItem?

**Comment by Hanzofm** [comment]
Hi, thanks for your time.


I have tried to do this:

```
import localForage from 'localforage';
@Injectable()
export class LocalStorageService {

  constructor() {
  }

  setHardcodedData() {
    return localForage.setItem('hardcodedData', 'randomtext');
  }

  
getHardcodedData() {
    return localForage.getItem('hardcodedData');
  }

  printDriver() {
    console.log(localForage.driver())
  }
```


And then on ionic page:

```
this.localStorageService.setHardcodedData()
        .then(finish => {})
.catch(error => {
console.log("JSON.stringify(error))
})
```


Before when app load (device is ready) I do:

```
setConfig(){
    localForage.config({
      driver: [localForage.INDEXEDDB,
        localForage.WEBSQL,
        localForage.LOCALSTORAGE],
      name: 'Project'
  });
  }
```

This is my Ionic info:


```
    @ionic/cli-utils  : 1.19.1
    ionic (Ionic CLI) : 3.19.1
global packages:
    cordova (Cordova CLI) : 7.0.1 
local packages:
    @ionic/app-scripts : 3.1.8
    Cordova Platforms  : android 6.4.0 ios 4.5.4
    Ionic Framework    : ionic-angular 3.9.2
System:
    Android SDK Tools : 26.1.1
    ios-sim           : 6.1.2 
    Node              : v10.0.0
    npm               : 5.6.0 
    OS                : macOS High Sierra
    Xcode             : Xcode 9.3 Build version 9E145 

```

This is my plugin list:

```
call-number 0.0.2 "Cordova Call Number Plugin"
com.googlemaps.ios 2.6.0 "Google Maps SDK for iOS"
com.unarin.cordova.beacon 3.6.0 "Proximity Beacon Plugin"
cordova-fabric-plugin 1.1.10 "cordova-fabric-plugin"
cordova-plugin-add-swift-support 1.6.0 "AddSwiftSupport"
cordova-plugin-app-event 1.2.1 "Application Events"
cordova-plugin-bluetooth-status 1.0.4 "Bluetooth status"
cordova-plugin-bluetoothle 4.4.3 "Bluetooth LE"
cordova-plugin-compat 1.2.0 "Compat"
cordova-plugin-console 1.1.0 "Console"
cordova-plugin-device 2.0.1 "Device"
cordova-plugin-email-composer 0.8.15 "EmailComposer"
cordova-plugin-firebase 0.1.25 "Google Firebase Plugin"
cordova-plugin-geofence 0.7.0 "geofence"
cordova-plugin-geolocation 4.0.1 "Geolocation"
cordova-plugin-googlemaps 2.1.1 "cordova-plugin-googlemaps"
cordova-plugin-hotspot 1.2.10 "Cordova HotSpot Plugin"
cordova-plugin-inappbrowser 2.0.2 "InAppBrowser"
cordova-plugin-network-information 2.0.1 "Network Information"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-statusbar 2.4.1 "StatusBar"
cordova-plugin-whitelist 1.3.3 "Whitelist"
de.appplant.cordova.plugin.local-notification 0.8.5 "LocalNotification"
es6-promise-plugin 4.2.2 "Promise"
ionic-plugin-keyboard 2.2.1 "Keyboard"
mx.ferreyra.callnumber 0.0.2 "Cordova Call Number Plugin"
```

**Comment by Hanzofm** [comment]
I have been able to reproduce the error on a emulator and log it.

The exception that it returns is:

```
vendor.js:1 ERROR Error: Uncaught (in promise): QuotaExceededError
    at c (polyfills.js:3)
    at polyfills.js:3
    at IDBTransaction.r.onabort.r.onerror (vendor.js:1)
    at IDBTransaction.H (polyfills.js:3)
    at t.invokeTask (polyfills.js:3)
    at Object.onInvokeTask (vendor.js:1)
    at t.invokeTask (polyfills.js:3)
    at r.runTask (polyfills.js:3)
    at e.invokeTask [as invoke] (polyfills.js:3)
    at p (polyfills.js:2)
```

From here, I have tried to do some test, with the phone with 400mb of available disk space, the error reproduce it.

With a 1,1Gb available space disk it works.

What would be the problem with the quota space?

**Comment by thgreasi** [comment]
Hmmm, I'm not sure what to suggest.
Do the webview present any modal to request additional storage?
Could you try setting a larger db size in your `.config()` call and see what happens?

**Comment by thgreasi** [comment]
Maybe @toffumat has an idea about this.

**Comment by thgreasi** [comment]
Maybe @tofumatt has some ideas on this.

**Comment by thgreasi** [comment]
Maybe [cordovaSqlite](https://github.com/thgreasi/localForage-cordovaSQLiteDriver) can give you better results on such lot storage conditions.

**Comment by tofumatt** [comment]
I recall the Cordova stuff being a bit weird sometimes but I'm not sure as I don't really use it much...

Are you setting a limit on the database? It might be worth asking the Cordova folks as I was under the impression they shim a lot of libraries and they might actually be intercepting these calls. 🤷‍♂️

**Comment by Hanzofm** [comment]
I am currently not setting any limit(consciously) to the storage limit. In your library the only way to specify the size of the database is with the attribute `size` of the `.config` method. According to the documentation this attribute only works with `WebSQL` driver.

With your library if change the driver priority to localStorage first the write works correctly this is due to localStorage not depends on quota limits but it have a 10mb fixed size limit.

Is there no way to tell the system the size of the quota you need in Indexeddb programatically?

I have tried this on various own apps and occurs the same, I think that this is not normal that with this available disk size the quota be unusable. May be a problem with the library?

[Related?](https://github.com/localForage/localForage/issues/819)

If I use `@Ionic/storage` I could use sql lite driver but this library uses `under the scenes` the `localforage` library and their driver order is [sqllite,**indexeddb**....] this worries me that it can fail also.

**Comment by thgreasi** [comment]
As I mentioned before, if this is an ionic app with Cordova, then the safest bet to avoid storage quota issues is to use [cordovaSqlite driver](https://github.com/thgreasi/localForage-cordovaSQLiteDriver).
Is there a reason you want to prefer indexeddb? Is this error originating from a browser?

**Comment by Hanzofm** [comment]
Hi,
Currently I am using cordova sqlite drivers a works fine.

I only say that the cordova way 'under the scenes' also uses localForage library and puts indexeddb driver as a second option just after sqlite driver.

I was using localForage on cordova apps because on several howto's/manuals recommends this library for cordova apps to use indexeddb.

I have not tried directly on browser via webapp but if you search localforage + QuotaExceededError you will can see several similar problems related to quota.

Thanks

**Comment by thgreasi** [comment]
> Currently I am using cordova sqlite drivers a works fine.

Should we close this and move the discussion to #819 ?

> I was using localForage on cordova apps because on several howto's/manuals recommends this library for cordova apps to use indexeddb.

That's probably in case you also want to make a website out of the same source code, in which case IndexedDB will be used in instead, as the second option after sqliteDriver. All in all, ionic storage [is just a facade over LF & the aforementioned cordovaSqliteDriver](https://github.com/ionic-team/ionic-storage/blob/master/src/storage.ts) that offers a slightly different API + some angular extras.
