### ISSUE TITLE
Google Closure Compiler fails because of a missing name variable

### ISSUE THREAD

**Issue by ashpr** [localForage/localForage#829]
Hey all,

I'm trying to compress my project via Google Closure Compiler via the advanced mode but it's sadly falling over because of this line here:

https://github.com/localForage/localForage/blob/e4b4c9427ef3e168c1f04fb29bb9e3468f4828ff/dist/localforage.js#L1712

The error is:
```
ERROR - variable name is undeclared
            t.executeSql('SELECT name FROM sqlite_master ' + "WHERE type='table' AND name = ?", [name], function (t, results) {
```
I'm inclined to agree with the compiler here, what is the name variable meant to be pointing to? I was going to make a PR but I can't really make sense of this function.

If anyone could help that would be really appreciated.

Many thanks,
Ash

**Comment by thgreasi** [comment]
Oh my... eslint thinks that we intend to you `window.name` there... I'm on it

**Comment by thgreasi** [comment]
I guess that everything still works since are doing `CREATE TABLE IF NOT EXISTS` anyway.

**Comment by thgreasi** [comment]
@ashpr opened #830 for this.
