### ISSUE TITLE
IndexedDB get blocked when another tab of same application is open

### ISSUE THREAD

**Issue by sugarshin** [localForage/localForage#833]
Hi,

The same thing as this issue is happening in my application.

https://stackoverflow.com/questions/30580958/database-get-blocked-when-another-tab-of-same-application-is-open

Is there way to solve?

**Comment by tofumatt** [comment]
If you're experiencing blocking during operations in another tab, that's to be expected. As mentioned in the StackOverflow issue: this is to preserve data integrity.

**Comment by pranavjain** [comment]
@tofumatt Is there a way to view the operations which are pending on the Db?

**Comment by tofumatt** [comment]
localForage doesn't expose that directly; it's meant to be a very high-level API without direct database access. If you wanted to check pending operations you might want to use a lower-level or more IndexedDB-specific library 😄
