### ISSUE TITLE
Support WebCrypto private key (not extractable object)

### ISSUE THREAD

**Issue by lakano** [localForage/localForage#844]
Hi,
Thanks for your useful package :)
Currently localForage can store a WebCrypto public key, but can't store a private key.
We should store it in IndexedDB, it's the goal, but not with localForage.
```
 import lf from 'localforage'
 
 const keys = await crypto.subtle.generateKey({ name: 'ECDSA', namedCurve: 'P-256' }, false, [ 'sign', 'verify' ])
 lf.setItem('publicKey', keys.publicKey) // works
 lf.setItem('privateKey', keys.privateKey) // doesn't works ( silently, no error at all )
```

Regards,

**Comment by tofumatt** [comment]
Which browser are you encountering this error in?  I don’t have much experience with WebCrypto, so I’m not aware of its subtleties :-)

- Matthew Riley MacPherson
tofumatt.com

**Comment by lakano** [comment]
Under Firefox 63.0b1 (dev edition) on GNU/Linux Fedora 28
And for the precision, even if we set the "extractable" parameter to "true", the private key still can't be saved.

**Comment by lakano** [comment]
Doesn't works on Windows 10 / Firefox 61 
Works under Chrome 68 ( even if extractable is set to false )

After some tests, this only happen with ECDSA algo, this works with the HMAC algo, I suppose it's a missing feature in Firefox, and it's not a localForage bug, so I close the ticket. 

Thanks for your reactivity!

**Comment by stephensong** [comment]
fwiw, I too encountered the same problem.  

I can successfully store non-extractable ECDSA private keys in indexedDB with Chrome, but not with Firefox or Safari.

It works ok with RSA-PSS though, so it's not a showstopper.

**Comment by autonome** [comment]
Here's the bug tracking this in Firefox. I updated the testcase there to cover ECDSA and ECDH keys stored in IndexedDB and it works now on release versions of both Firefox and Safari.

https://bugzilla.mozilla.org/show_bug.cgi?id=1434898#c13
