### ISSUE TITLE
_tryReconnect, forage._dbInfo is null (caused by Failed to execute 'transaction' on 'IDBDatabase': The database connection is closing.)

### ISSUE THREAD

**Issue by eugeniumegherea** [localForage/localForage#846]
Using localforage 1.7.2 on chrome 69 
In a angular 2 application of ours (where a database can have at least 30 stores), I found a pattern to reproduce `Failed to execute 'transaction' on 'IDBDatabase': The database connection is closing.` 100% of the times.

I want to share what I've found so far:
- To reproduce I basically do a 'Clear storage' from chrome dev tools and refresh the page.
- The error is magically gone on the next page refresh
- There is an `InvalidStateError` (see images), which calls `_tryReconnect` https://github.com/localForage/localForage/blob/3e1d6e70a001e0f057d816740c7bc9167e2f0711/dist/localforage.js#L792
- In `_tryReconnect` function, for some reason, in loop, `forage._dbInfo` is null, which throws `TypeError: Cannot read property 'db' of null` (see images)
https://github.com/localForage/localForage/blob/3e1d6e70a001e0f057d816740c7bc9167e2f0711/dist/localforage.js#L757
- Tried to handle `forage._dbInfo` null, but the same error (cannot read db of null) happened in other part of the code
- At this point, I think the issue might hide in race conditions and fast concurrent `localforage.createInstance` and writing to that store. (We have a kind of sync mechanism, which recreates IDB state from API, so we basically create multiple stores at the same time)

Do you have any ideas what this may be?
Thanks

Failed to execute 'transaction' on 'IDBDatabase': The database connection is closing
![screen shot 2018-09-12 at 6 17 00 pm](https://user-images.githubusercontent.com/25582225/45437105-f082a200-b6bc-11e8-8dee-b77333490fc3.png)
![screen shot 2018-09-12 at 6 18 05 pm](https://user-images.githubusercontent.com/25582225/45437216-19a33280-b6bd-11e8-99f3-a2b6cea692ed.png)

See contents of `dbContext` object
![screen shot 2018-09-12 at 6 23 29 pm](https://user-images.githubusercontent.com/25582225/45437407-6ab32680-b6bd-11e8-9e4e-090da5fd4a4c.png)

See contents of each `forage` from `forages` array
![screen shot 2018-09-12 at 6 28 25 pm](https://user-images.githubusercontent.com/25582225/45437475-8caca900-b6bd-11e8-83f9-60cb8fe2e98e.png)

**Comment by korlend** [comment]
hi. what was the problem?

**Comment by eugeniumegherea** [comment]
Our code had a lot of concurrency problems, which caused inconsistent state when cleaning db and inserting again. What was weird is that it crashed in the localforage itself, with not relevant stacktrace

**Comment by korlend** [comment]
I had the same issue.
When I subscribe on .ready of localforage storage, and then call .setItem it cause error. So I wrote my own ready promise.
```javascript
  onready () {
    if (this._ready) {
      return new Promise((resolve, reject) => resolve(true))
    } else {
      return new Promise((resolve, reject) => {
        this._localForageCollection.ready(() => {
          const repeater = () => {
            if (this._localForageCollection._dbInfo) {
              resolve(true)
              this._ready = true
              return
            } else {
              const tm = setTimeout(repeater, 500)
              clearTimeout(tm)
            }
          }
          repeater()
        })
      })
    }
  }
```

**Comment by rebendajirijr** [comment]
Is there any official fix?

**Comment by tofumatt** [comment]
I don't think the issue here was from localForage itself, although if you can provide a reproducible test case we can use to diagnose the issue—if it's a problem with localForage—that'd be great.

Otherwise I don't think this needs a fix as it didn't seem to be directly caused by localForage's code.
