### ISSUE TITLE
Convert localForage from Promises to Observable v6

### ISSUE THREAD

**Issue by 51303014** [localForage/localForage#849]
I have an issue when using localforage library for angular v6 with Akita state (rxjs v6).
When I setItem save data into IndexDB but I refresh the page and then in IndexDB be to delete data.
First I convert localforage to observable and then I use the state of Akita save data into indexDB.
This is my code: 

I hope team able to support issue. 
Thanks very much

**Comment by tofumatt** [comment]
I'm not familiar with RxJS at all, so I'm not able to really help out with this. Have you tried contacting any RxJS support channels? I can't really tell what's happening here, but I don't think it's specific to localForage, it seems like an issue with how this is coded in RxJS... but I'm not sure how to help.

Sorry 😞

**Comment by 51303014** [comment]
Ok. Tks !
