### ISSUE TITLE
Chrome Packaged App

### ISSUE THREAD

**Issue by SteveBrooker** [localForage/localForage#850]
I have been using localForage for 4 years in a chrome packaged app and up until now I have ignored the error message "localStorage is not available in packaged apps". How could I easily create a variant of localForage that does not test for the presence of localStorage

**Comment by tofumatt** [comment]
In terms of how could you "easily" do it I don't think there's an answer. We try to gracefully check for storage mechanisms and when they are not discovered we fallback to others, but we don't really have a design goal to entirely exclude them in the codebase.

That said, perhaps `localforage.setDriver([localforage.INDEXEDDB , localforage.WEBSQL]);` would work? It should prevent the error as support for the driver wouldn't be checked... I think?

But aside from that we don't really have a build system driver-exclusion guide. You could check out the repo and build your own version without `src/drivers/localstorage.js`, but that's probably the only way, sorry 😞

**Comment by SteveBrooker** [comment]
Thanks. 
I just tried a global replace of "localStorage" with "localStore" in the minified localForage.js which of course will be undefined but as this is tested for already the code still works fine.
This change effectively supresses the chrome app error message.

**Comment by tofumatt** [comment]
Oh, interesting! I think if you exclude `localStorage` from the drivers to use with the function I referenced it might work as well, not sure 🤷‍♂️

I'd be curious to hear about it! If it does maybe we could add it to some docs.

**Comment by SteveBrooker** [comment]
Unfortunately excluding localStorage using your additional line of code, does not suppress the chrome app error message

**Comment by tofumatt** [comment]
Ah, darn! Okay, thanks for letting me know.

**Comment by thgreasi** [comment]
Maybe we should allow imports like lodash does. Perhaps we could allow importing only the drivers that we are interested in & the LocalForage class and then use defineDriver to instantiate it.
That's for v2.0 probably.

**Comment by tofumatt** [comment]
I would dig that, there's certainly folks who want localForage more for the API and not for the driver support; cutting down on the bundlesize would please them.
