### ISSUE TITLE
Use setItem method in localforage when refresh page then data without in IndexedDB

### ISSUE THREAD

**Issue by 51303014** [localForage/localForage#851]
I'm using library localforage in angular 6 with Rxjs. But when I use setItem method in lib.
When I refresh page then data without in IndexedDB.

```

When I setItem then value saved into IndexedDB but I refresh page and add a new value . 
In IndexedDB has been remove old value. 
I don't know why it's happen ? 
Please help me ! 
Thanks

**Comment by tofumatt** [comment]
Is the issue that your new value isn't being saved?

I don't see you waiting for the return result of `locaforage.setItem` in your code; maybe you are refreshing the page before save?

**Comment by 51303014** [comment]
> Is the issue that your new value isn't being saved?
> 
> I don't see you waiting for the return result of `locaforage.setItem` in your code; maybe you are refreshing the page before save?

I don't think so.
Because I saved value but when I refresh the page then Value in IndexedDB till it.
Result: When I add a new value. 
A new value still adds into IndexedDB but the old value has been removed. 
So that I don't know reason ??

**Comment by tofumatt** [comment]
Is the storage key you’re using the same? setItem will overwrite values if they share the same key.

- Matt (Sent from mobile)

**Comment by 51303014** [comment]
> Is the storage key you’re using the same? setItem will overwrite values if they share the same key.

Yes. the storage key is the same. But why the first I setItem into storage key it's still saved and doesn't overwrite. After that I reloaded the page then it's happened (setItem will overwrite ???).
In the document you are said: API of localforage the same localStorage! 
This is an example when I use localStorage and localForage.
In the first localForage work fine but when the refreshed page I use setItem then data will overwrite.
the reason why? 
![screen shot 2018-10-16 at 6 35 34 pm](https://user-images.githubusercontent.com/17430644/47013616-0418a100-d172-11e8-951c-4937b0245bef.png)
Thanks !

**Comment by tofumatt** [comment]
Could you provide a code sample to show the issue you’re encountering? I don’t quite follow the issue, but if you call `setItem()` with the same key: its value will be overwritten. That’s working as normal :-)

**Comment by 51303014** [comment]
> Could you provide a code sample to show the issue you’re encountering? I don’t quite follow the issue, but if you call `setItem()` with the same key: its value will be overwritten. That’s working as normal :-)

This is code sample: I use localforage in service folder.
https://stackblitz.com/edit/akita-todos-app-39wuej?file=src%2Fapp%2Ftodos%2Fstate%2Ftodos.service.ts 


This is link for test localforage (IndexedDB) : 
https://akita-todos-app-39wuej.stackblitz.io/todos 

Step to work : 
1. Input value and enter.
2. Open tab application in IndexexDB 
3. The value saved but when refresh page value has been removed

And you observe when you input a lot of value and I call `setItem()` with the same key: it value won't be overwritten.

When I refreshed the page: values of IndexedDB has been removed.
 Please help me! Thanks !

**Comment by tofumatt** [comment]
Did you mean to close this issue? If so: did you find out what the problem was? :-)

**Comment by 51303014** [comment]
> Did you mean to close this issue? If so: did you find out what the problem was? :-)

Yes. I found out this issue.  So that I closed this issue. 
The problem is localforage (Promise). And the type of the constructor is a state so it isn't converted the value.
Thank you for helping me.
