### ISSUE TITLE
how use it in vue but withour webpack,npm just cdn

### ISSUE THREAD

**Issue by all-** [localForage/localForage#861]

**Comment by tofumatt** [comment]
You can include localForage on your site using a CDN like CDNJS: https://cdnjs.com/libraries/localforage

Hope that helps! 😄

**Comment by tofumatt** [comment]
I’m not sure I understand what you’re trying to do, but we can only provide support for localForage in this repo. If your issue is related to VUE or a VUE localForage package you should file an issue with them. I’m sorry but I can’t help much with your question ☹
