### ISSUE TITLE
Working with multiple setters 

### ISSUE THREAD

**Issue by ArielGueta** [localForage/localForage#866]
Hey,

Thanks for this great library. I have a question. Let's say I called twice to `setItem`, for example:

```js
localForage.setItem('key', value)`.then();
localForage.setItem('key', differentValue).then();
```
There is a chance that the first call will override the second or the library takes care of this under the hood?

Thanks.

**Comment by tofumatt** [comment]
Yes, that is correct; the first value could be written after the second. The library doesn't keep a log of which operations have run and their order.

If you're using ES7 with async/`await` syntax, you can ensure they run in the correct order using:

```js
await localForage.setItem('key', value);
await localForage.setItem('key', differentValue);
```
