### ISSUE TITLE
Mozilla: No available storage method found when 

### ISSUE THREAD

**Issue by rameden** [localForage/localForage#867]
I am running `    "localforage": "1.7.2"` in my APP. If I am using Mozzila and have my Cookies and Site Data preferences set to `Block Cookies and Site data => Cookies from Unvisited Websites` I get the following error in console:

```
Error: "No available storage method found."
```

I have a file where I am defining and setting a new driver.
```
import * as localforage from "localforage";
import * as sessionStorageDriver from "localforage-driver-session-storage";
import { localForageConfig } from "common/constants/localForageConfig";

// override localForage default config
const localForageDriver = localforage.createInstance(localForageConfig);

// set localForage driver for sessionStorage
localForageDriver.defineDriver(sessionStorageDriver).then(() => {
  return localForageDriver.setDriver(sessionStorageDriver._driver);
});

export default localForageDriver;
```
When trying to return `console.log(localforage.driver())` it is returned as `null`

Any help as to what I can try to fix this would be more than welcome. 

Thanks!

**Comment by tofumatt** [comment]
Does session storage work when cookies are enabled? Are you loading `localForage` JS files from another origin? My instinct is that there's something happening here with origins, because localForage doesn't seem to think you have a valid driver around.

Could you provide a URL we could test from to replicate the issue?

**Comment by rameden** [comment]
It does work when cookie are enabled. This is an internal app sadly, so I can't provide a link. 

Our app is being loaded within an iframe of a larger app. I believe you would be correct in assuming something is happening with origins. Is there a way we can "force" a driver?

**Comment by tofumatt** [comment]
If it works with cookies enabled then I think that's the trick. I'm under the impression that session storage has a same-origin policy, so loading it in an iFrame, especially with cookies disabled, might be enough to make things not work. I don't think there's much of a solution there if you have to force session storage 😞

There's no way to force a driver that is disallowed by a browser's security model, so you'll need to either have different settings/requirements for users, different infrastructure to load your app, or a different storage driver.
