### ISSUE TITLE
It is recommended to increase the interceptor function.

### ISSUE THREAD

**Issue by czy66545360** [localForage/localForage#868]
Generally speaking, when we are doing the management system, when the data is stored offline, the data needs to be encrypted and decrypted, so we hope to have a unified portal interception and response interception method. I don't know what to think about?

**Comment by sdrissen** [comment]
Data security is a hot topic.
But it is hard to archive.
How do you want to save the encryption key?
Do you want to force every user to enter it, for each Tab?

**Comment by tofumatt** [comment]
Encryption and decryption isn't something we'll be building into localForage directly; we simply store the data. It's up to other libraries to handle any encryption 😄
