### ISSUE TITLE
Chrome for Android 30

### ISSUE THREAD

**Issue by CodingAnonymous** [localForage/localForage#875]
Hi, as stated in the docs (https://github.com/localForage/localForage/wiki/Supported-Browsers-Platforms) the minimum Chrome Version for Android is 32. Is there a possibility to support Chrome Android 30 as well? A lot of devices running Android Kitkat (4.4) are using Chrome Android 30, so I can't save the data there in localForage.

Any help is highly appreciated!

**Comment by sdrissen** [comment]
What is the problem?
Is there anyway to test localForage under Chrome Android 30 without buying an old Android phone?

**Comment by tofumatt** [comment]
Unfortunately I can't say for sure if older versions support localStorage, which is essentially our minimum viable storage backend. I believe localForage will still _run_ on these older browsers using the memory storage fallback, but I can't guarantee that.

Support for `localStorage` in pre-5.0 Android versions isn't clear: https://caniuse.com/#search=localstorage

But there's no plan to add support for a browser that old, sorry about that.

If localStorage _is_ available on those versions localForage should run just fine. Feel free to update us in this issue if you get it working, but if it isn't working we won't be able to add support. Sorry!
