### ISSUE TITLE
The requested version (1) is less than the existing version (2).

### ISSUE THREAD

**Issue by valesist** [localForage/localForage#877]
Hi,
i've two applications:

- http://localhost/test1
- http://localhost/test2

When i open F12 in Chrome, tab Application, i see that applications have two different version: 1 and 2.
![image](https://user-images.githubusercontent.com/23034982/52860748-9cc72980-3130-11e9-80d3-b6bcffa59df1.png)
![image](https://user-images.githubusercontent.com/23034982/52860775-b36d8080-3130-11e9-9110-7cf196eef854.png)

Can you explain to me what this version refers to?
If I open test2 and then I open test1, any call to localforage goes in exception: "**The requested version (1) is less than the existing version (2).**"

Thanks in advance
Valentina

**Comment by tofumatt** [comment]
You can read about the version param here: https://localforage.github.io/localForage/#settings-api-config

It's not used for much but you are getting that error because you're using mismatched version numbers. You probably don't need to be using the version param at all.
