### ISSUE TITLE
SetItem is not working in Vue project.

### ISSUE THREAD

**Issue by ZhenZY** [localForage/localForage#885]
My code is as follows.
```
import localforage from 'localforage';
let localDB = localforage.createInstance({
  name: 'historyRecords'
});
localDB.setItem('testKey', 'testValue').then(() => {
  console.log('Is not working here, why?);
});
```

**Comment by tofumatt** [comment]
What is your browser/OS? This code should work and does in tests so it’s likely not a localForage issue; there is probably an issue with the underlying storage.

Is there anything in your console logs?

- Matthew Riley MacPherson
tofumatt.com

**Comment by ZhenZY** [comment]
Please excuse me.I made a low-level mistake.It's all right now.
