### ISSUE TITLE
is possible to have AUTO_INCREMENT id to data stored with this mechanism?

### ISSUE THREAD

**Issue by bkrajendra** [localForage/localForage#886]
Im using LocalForage latest for mobile application with ionic 4 and angular 7.
Is there any way to have AUTO_INCREMENT id to data stored with this mechanism just like SQL data type we have.

Or any other mechanism we can get the unique id for each record we store.

**Comment by tofumatt** [comment]
Sorry, no. localForage is a very basic key/value store (think like Redis or something similar on a server). You have to manage IDs/keys yourself; we don't have any plans to introduce something like that as it would greatly complicate the database.
