### ISSUE TITLE
DOMException: Connection to Indexed Database server lost. Refresh the page to try again

### ISSUE THREAD

**Issue by oarsheo** [localForage/localForage#887]
IOS 12.2  ( Cordova ) 
`DOMException: Connection to Indexed Database server lost. Refresh the page to try again`

the database crashes from time to time
Has anyone encountered this problem?

**Comment by tofumatt** [comment]
This seems a Cordova-specific problem; without knowing much about how it works, it reads like it is trying to connect to an IndexedDB database being served through a proxy? IndexedDB doesn't really run a "server" per-se in normal usage.

If you could provide steps to reproduce we can re-open this issue, but this doesn't strike me as a localForage bug.

**Comment by zspitzer** [comment]
this is a known webkit/safari bug https://bugs.webkit.org/show_bug.cgi?id=201483
