### ISSUE TITLE
IndexedDB can not be connected or force closed.

### ISSUE THREAD

**Issue by pingyuanChen** [localForage/localForage#896]
![image](https://user-images.githubusercontent.com/8485981/61429043-4b2d0000-a957-11e9-8a9e-cec777a3b9e9.png)

**Comment by tofumatt** [comment]
Managing the connection status for a database backend is outside the scope of localForage. I’m curious to know what got you into this state (as that seems like a bug). But we aim to be a very simple and high-level API, so I don’t want us the introduce concepts like database connections.

If you could file a new issue explaining how you got to that “stuck” state though that’d be useful! Thanks 🙂
