### ISSUE TITLE
Support Data Import/Export

### ISSUE THREAD

**Issue by Jamie0** [localForage/localForage#898]
It would be nice to have the ability to export and import data 'dumps' from localForage. This would allow an entire storage instance to be moved between different environments in a standardised format. 

This would also be useful when using localForage in testing environments to pre-seed the store with known data, making it trivial to construct test scenarios from an application. It could also be useful in allowing applications to 'sync' a backup of their settings to a server (note that real-time sync and equivalents are out of scope of this feature request). 

#115 touched on this, but never made any progress before it was closed.

**Comment by tofumatt** [comment]
The reason that would be annoying to implement is localforage doesn’t actually keep track of all of your data (eg the names of the databases you’ve made, keys, etc). If you knew each dB you could iterate through the keys and export the data as JSON though. I don’t think it’s a candidate for a core feature (it’s useful, but a bit niche).

But a plug-in/extension that implemented that would be cool, for sure.

I think we wouldn’t do it in the core library though. I’ll close it here but if someone made a library that did this I’d happily add it to the README :-)

**Comment by tofumatt** [comment]
Side note: we could add the repo to the localForage organisation for extra visibility if someone was happy to maintain it 😊
