### ISSUE TITLE
Localforage doesn't work with newer versions of Safari.

### ISSUE THREAD

**Issue by leesc81** [localForage/localForage#905]
I upgraded my Safari version to a new version a few days ago.
(localForage ver: 1.7.3, safari ver: 13.0.1, mac os ver: 10.14.6)

I get an error in my code below.
```js
localforage.setItem ('selected_product_type', 'phonecase', function (err) {
});
```

Error message:
InvalidStateError: Failed to read the 'error' property from 'IDBRequest': The request has not finished.
localforage.min.js: 574

My site stopped working due to this error.
What happened?

**Comment by tofumatt** [comment]
Hi there! Was everything working before this update of Safari? I notice the code you used as an example had a space before the parens, which I don't think will work as expected. But I'm guessing that's just a typo in the issue, correct?

Is this working on other browsers? Is it possible something else on your site has interacted with the IndexedDB database? Or maybe you're in Private Browsing Mode?

I went to https://localforage.github.io/localForage/, opened a console, and ran your code without an error:

<img width="550" alt="Screenshot 2019-09-26 14 47 52" src="https://user-images.githubusercontent.com/90871/65693791-bfc59e80-e06c-11e9-9c0a-384f33162672.png">

I'm using Safari `Version 13.0.1 (14608.2.11.1.11)` on MacOS 10.14.6.

**Comment by leesc81** [comment]
Sorry.
There seems to be a problem with my webpack build.
The new build made the problem go away.
Thank you.

**Comment by tofumatt** [comment]
No worries, thanks for letting us know!

**Comment by ekokotov** [comment]
I have the same issue. Version 13.0. driver: asyncStorage:
InvalidStateError: Failed to read the 'error' property from 'IDBRequest': The request has not finished.
with localStorage driver everything works fine

**Comment by Jhonsem** [comment]
@leesc81  how to fix it?

**Comment by ekokotov** [comment]
@Jhonsem just as a quick fix for now, you can set driver to localStorage
