### ISSUE TITLE
Uncaught NotFoundError: Failed to execute 'transaction' on 'IDBDatabase': One of the specified object stores was not found.

### ISSUE THREAD

**Issue by ocombe** [localForage/localForage#91]
There is a bug related to the commit https://github.com/mozilla/localForage/commit/e6aadde9716f987692af12f0ddc6aa5819e69d5a : you have renamed the DB to `localForage` with a capital F, and I get this weird error on Windows...
I changed it to lowercase `localforage` and no more bug ...
The WebSQL DB is also named with the lowercase version.

**Comment by brandonros** [comment]
I've never experienced this issue until today and now I am receiving it like crazy.

Mac OS X 10.11.1

Version 48.0.2564.23 beta (64-bit)

What's weird is the exception is thrown and caught by the debugger, but it doesn't seem to have any negative side effects. All of the code seems to work.

**Comment by siddo420** [comment]
here is one way to reproduce it on MacOSX Chrome:

Using example in Readme.
```
var store = localforage.createInstance({
  name: "nameHere",
  storeName: 'one'
});

var otherStore = localforage.createInstance({
  name: "nameHere",
  storeName: 'two'
});

store.setItem("key", "value");
otherStore.setItem("key", "value2");
```

**Comment by siddo420** [comment]
Looks like it works fine on Safari, however multiple stores (storeNames) of the same names were created.
![screen shot 2016-01-05 at 9 43 09 pm](https://cloud.githubusercontent.com/assets/6943328/12133657/5983f3f8-b3f5-11e5-9dba-cc4d649df85f.png)

**Comment by siddo420** [comment]
FF does not throw an error but only creates the first table/store 'one'.

**Comment by tofumatt** [comment]
Whoa, the Safari bug is particularly weird, creating multiple tables with the same name.

**Comment by sebweaver** [comment]
@siddo420 Which version do you use?

**Comment by siddo420** [comment]
@sebweaver 1.2.6

**Comment by sebweaver** [comment]
Please upgrade to the latest version, multiple storages on the same db has been fixed [here](https://github.com/mozilla/localForage/pull/452) and released in version 1.3.

**Comment by siddo420** [comment]
Works in Safari but not in Chrome (haven't tested with FF yet). Please make sure you delete your database before testing else it wont show the error.

```
<html><head><meta charset="utf-8">
<script type="text/javascript" src="{{fileserver}}js/vendor/localforage/dist/localforage.min.js"></script> 
</head><body></body></html>
```
I tried using *-no-promises lib as well but same result.

The code I used (same as above):
```
var store = localforage.createInstance({
  name: "nameHere",
  storeName: 'one'
});
var otherStore = localforage.createInstance({
  name: "nameHere",
  storeName: 'two'
});
store.setItem("key", "value");
otherStore.setItem("key", "value2");
```
Error (with nopromises.js):
```
Uncaught (in promise) DOMException: Failed to execute 'transaction' on 'IDBDatabase': The database connection is closing.(…)(anonymous function) 
@ localforage.nopromises.js:925
```
Error (regular):
```
Uncaught (in promise) DOMException: Failed to execute 'transaction' on 'IDBDatabase': The database connection is closing.(…)(anonymous function) 
@ localforage.js:1608
```

quick ref:
```	                
return value;
}).then(function (value) {
var transaction = dbInfo.db.transaction(dbInfo.storeName, 'readwrite'); //<--1608
var store = transaction.objectStore(dbInfo.storeName);
```

**Comment by sebweaver** [comment]
Ok, It looks identical to issue #492 now. I think we should continue there.

**Comment by tundesky** [comment]
how to solve the problem of uncaught dom exception failed to execute idbDatabase as one of the object store was not found

**Comment by thgreasi** [comment]
What version of localforage are you using?
