### ISSUE TITLE
how to create index on setItem and retrieve item 

### ISSUE THREAD

**Issue by mikeyyyzhao** [localForage/localForage#911]
Hi guys, thanks for the great library. 

Currently, we're storing our data with event_id as the key and the event object as the value. However, as our data is growing, we want to start pulling data between two dates. I think in IndexDB you could create indexes on entry and then pull data based on that index. Essentially creating another key to pull events from. The new table would look something like key: event_id, index: date, value: event_details and we would be able to pull data through indexKeyRange. Is there a way to do that through LocalForage? Both to store the data with an index as well as being able to pull it through the index. Thanks in advance for the help.

**Comment by vinikatyal** [comment]
https://github.com/liqwid/localforage-indexes

**Comment by tofumatt** [comment]
localForage on its own is a very simple key/value store, with no built-in support for indexes, foreign keys, etc. In order to build a database with more complex requirements I'd recommend something like [PouchDB](https://pouchdb.com) or [Dexie](https://dexie.org).
