### ISSUE TITLE
no 'local-forage-detect-blob-support' object store

### ISSUE THREAD

**Issue by stepet80** [localForage/localForage#916]
Is it possible to not have an object store 'local-forage-detect-blob-support' in the database.
The reason is that we want to use localForage to put key value items in the object store. But we will probably be using idb to do more complex management. So for this we would like it to be as clean as possible.

**Comment by stepet80** [comment]
If I look at the code it doesn't seem to be possible. It would be cool to have a localforage option to ommit this so the check is not done...

**Comment by tofumatt** [comment]
That object is required to determine support for blob storage so is required. Generally speaking we don't really "support" accessing the localForage database directly—it's possible but not really an intended use-case as localForage serialises values depending on support, stores things like the blob support bit, etc.

localForage does its best to limit how much data it stores but unfortunately I don't think it's on the roadmap to remove the little bits we do store. That said you should be able to check through the code and find any special stores we create and work around them in your own code 😄
