### ISSUE TITLE
Using .clear() on indexedDB doesn't work on chrome

### ISSUE THREAD

**Issue by stratosphr** [localForage/localForage#924]
Hello everyone,

I tried to use localForage.clear() using the indexedDB driver on chrome (on Linux).
If I put a callback, the callback is indeed called but clearly the storage is not cleared.

I tried using the WebSQL on chrome and it works perfectly fine.
I also tried using Firefox and it also works fine.

So the bug seems to come from chrome + indexedDB.

**Comment by qkreltms** [comment]
Did you solved your issue? Then how to?

**Comment by geoidesic** [comment]
It works for me in Chrome. Maybe show some code.
