### ISSUE TITLE
Bower is deprecated. Use Yarn instead

### ISSUE THREAD

**Issue by nainardev** [localForage/localForage#929]
In docs website, ```bower``` is used in Installation section, add ```yarn``` instead

**Comment by tofumatt** [comment]
`yarn` installation doesn't need any special instructions; yarn users can use `yarn add` install of `npm install`. If you want to create a PR with yarn instructions though feel free; `bower` support will likely be dropped in v2.

**Comment by nainardev** [comment]
Atleast remove `bower` in docs
