### ISSUE TITLE
Release in ESM format

### ISSUE THREAD

**Issue by nainardev** [localForage/localForage#940]
>No web-optimized "module" entrypoint was found in its package.json manifest"

![Screenshot_20200313-000704](https://user-images.githubusercontent.com/59839368/76556046-d34faf00-64be-11ea-9371-48fc346a2f83.png)

**Comment by quentincaffeino** [comment]
Wouldn't be enough adding this line to package json?
`"module": "src/localforage.js",`
I tried it and it worked.

**Comment by tofumatt** [comment]
Works for me! Could you open a PR? I'll happily approve it and ship a new release with it today 😄

**Comment by tofumatt** [comment]
1.8.0 has been published and is available on NPM. Thanks! https://www.npmjs.com/package/localforage

**Comment by Samuel-Therrien-Beslogic** [comment]
Since https://github.com/localForage/localForage/pull/977 has been reverted, this should likely be re-opened.
IE11 is also finally dead

**Comment by emeryao** [comment]
+1
any updates here?

**Comment by sysmat** [comment]
any updates?
