### ISSUE TITLE
Need atomic transaction operation support

### ISSUE THREAD

**Issue by shmilyoo** [localForage/localForage#941]
I need to continuously write logs to the database. After accumulating a certain amount of logs, I need to upload to the backend and clear the frontend data.
This requirement requires atomic transaction operation support。

localForage is amazing, make it better please

**Comment by tofumatt** [comment]
As mentioned in #17—I think this is out-of-scope for localForage's current aim/goals of creating a simpler API to access underlying browser storage APIs. I think someone could build an atomic layer *on-top* of localForage, but I don't see it as being in-scope for the core library itself.

If someone had a patch ready that fully implemented atomic commits with tests I wouldn't say no I suppose (if it didn't harm the filesize/etc.), but for now I don't see the core library committing to atomic/transaction support especially when it would need to implement its own to work with `localStorage`. We couldn't rely on underlying database support for these things in WebSQL/IndexedDB (if they exist there, I'm not sure if they do honestly!)

Closing as a duplicate, but if anyone _does_ work on this as either an extension or something for the core library, please do share it here or in #17! 😄
