### ISSUE TITLE
List of stores

### ISSUE THREAD

**Issue by srinivasdandu** [localForage/localForage#950]
I created multiple instances of the localForage that point to different stores using createInstance. So I need to delete some of the stores. How can I find out and list out the stores created? Is there any way get the list of the stores.

**Comment by tofumatt** [comment]
If you created different stores with different instances of localForage, it's up to you to manage those instances. A localForage instance (with a `name`, `storeName`, etc.) keeps track of the data in its database, but there isn't a metastore with all existing stores available.

Sorry about that, but if you want that kind of list you'll need to manage it yourself. You can keep it in its own store, though! 😄
