### ISSUE TITLE
Can we make localStorage driver off-thread for performance improvement

### ISSUE THREAD

**Issue by himanshu199728** [localForage/localForage#956]

**Comment by himanshu199728** [comment]
@thgreasi Can we add this feature in this library.

**Comment by tofumatt** [comment]
If you're talking about introducing Web Workers to localForage to off-load the storage get/set calls: no. I don't think that's where any localForage performance issues exist for smaller apps, and larger apps can feel free to move their storage calls to workers if they like. But I don't think it's a reasonable default to require Web Workers for localForage. A large selling point for localForage is ease-of-use, and there are existing things like batch requests that would improve localForage performance we should tackle first.
