### ISSUE TITLE
Add CacheStorage driver as another option for user to do offline storing of data

### ISSUE THREAD

**Issue by himanshu199728** [localForage/localForage#957]

**Comment by himanshu199728** [comment]
@thgreasi Can we add this feature in this library.

**Comment by tofumatt** [comment]
The `Cache` API is meant for `Request`/`Response` objects, as I understand it, and not for generic storage. See: https://developer.mozilla.org/en-US/docs/Web/API/Cache.

It's in the name; the `Cache` backend serves as a way for responses to be cached temporarily, but it isn't generic storage. I'm not sure why we'd want to add support for `Cache` storage—what benefits would it bring over `IndexedDB`?

(That said, you can write your own custom driver for localForage; see info about custom drivers in the README: https://github.com/localForage/localForage#custom-drivers)

**Comment by aeharding** [comment]
As of iOS 14, `CacheStorage` is the sole means of sharing data between Safari an an "installed PWA" (added to homescreen). This is important if you don't want the user to re-login, etc.

More reading:

 1. https://firt.dev/ios-14/#storage-shared-with-safari
 2. https://stackoverflow.com/questions/62669966/how-to-maintain-login-status-in-a-pwa-initially-loaded-via-safari-14-ios-14
 2. https://stackoverflow.com/questions/21109615/ios7-safari-saving-to-home-screen-and-persist-token

Not saying localForage *should* support this, but there now is a valid, unique use case for this driver. 🙂
