### ISSUE TITLE
Is vendor-prefixed indexedDB still supported?

### ISSUE THREAD

**Issue by buko106** [localForage/localForage#962]
In the current master branch, vendor-prefixed version of indexedDB is considered and resolved in [idb.js](https://github.com/localForage/localForage/blob/5cded532fb257bb49157e4d14e5322d3c1d3b911/src/utils/idb.js
).

However, isIndexedDBValid seems to return false if window.indexedDB (not vender-prefixed) is undefined.

https://github.com/localForage/localForage/blob/8c47ed0f5b6c022ffbabe54bf18553d759d9cd70/src/utils/isIndexedDBValid.js#L32

Is vendor-prefixed indexedDB still supported?

**Comment by tofumatt** [comment]
Yes, localForage 1.x still supports vendor-prefixed IndexedDB, though they are only used in browsers that are quite old at this point.

The `IndexedDB` variable referenced there is obtained from `getIDB()` in the `utils/idb.js` file, so it actually gets the vendor-prefixed version if `indexedDB` is not available.

That said, I think we'll be dropping support for vendor-prefixed versions in 2.0. All modern browsers have IndexedDB exposed without a prefix, and have for several years. 🙂
