### ISSUE TITLE
Look, a new Chrome extension for localForage!

### ISSUE THREAD

**Issue by jgillick** [localForage/localForage#969]
I wasn't sure where to put this to let you know, so here it is...

I've created a Chrome extension to make it easy for people to view/edit their localForage stores.

https://chrome.google.com/webstore/detail/nebnfengdjloaaacibpdnjmahkobfeoe

**Comment by tofumatt** [comment]
Whoa, neato! That's really cool 😄

I'd love to see a Firefox version as well, given how involved Mozilla was with this project initially 🙂 

I'm currently working away on major improvements to localForage's internals and on a new website with @sarahmonster. I'll call this out on the new site 👍 

(I'll close this for now, but I've made a note of it in my website redesign notes, which will eventually live in https://github.com/localForage/localforage.org)

**Comment by jgillick** [comment]
From what I can tell, Firefox follows similar conventions for extensions, so making this work for both could be trivial. I'll give it a try when I have a bit of time.

**Comment by tofumatt** [comment]
Yup! I actually worked at Mozilla on the Add-ons team during the migration to the WebExtensions API 🙂

Hopefully it's pretty straightforward, but if the project is open-source, feel free to ping me in any issues if you want a second set of eyes 😄

**Comment by jgillick** [comment]
@tofumatt That's good to know. I used to build addons back in the early XUL days. The project is open-source, so I'll let you know when it's close and get your eyes on it. 

I did a quick test yesterday and the UI loads alright and it just looks like there might be some compat updates needed on the [crx-bridge](https://github.com/NeekSandhu/crx-bridge) library. (I'm pulling together a PR for that now, too)

Stay tuned. 😄

**Comment by jgillick** [comment]
The crx-bridge project accepted my PR and I've updated the extension to work in Firefox ([changes](https://github.com/jgillick/LocalForageExplorer/commit/ddb5b5c011c8b6c668d3fc461ad38784bd56b422)). Now the extension is awaiting approval on the Mozilla developer hub.

**Comment by jgillick** [comment]
And the Firefox version of the extension is live! 
https://addons.mozilla.org/en-US/firefox/addon/localforage-explorer/
