### ISSUE TITLE
What's the max limit I can set to size in localForage Config?

### ISSUE THREAD

**Issue by yashwin** [localForage/localForage#996]
example: 

```
localForage.config({
    size: 49807360, // Size of database, in bytes. WebSQL-only for now.
});
```

**Comment by tofumatt** [comment]
The limits are somewhat browser and backend-dependant. For instance, `localStorage` has a 5MB limit I believe.

https://developer.mozilla.org/en-US/docs/Web/API/IndexedDB_API/Browser_storage_limits_and_eviction_criteria#Storage_limits has some info on IndexedDB limits, but the short answer is they're quite high 🙂 

localForage itself doesn't set any limits beyond what the browser does.

**Comment by yashwin** [comment]
@tofumatt Thanks mate
